{{
  config(
    materialized = 'table',
    tags = ['PLAYER', 'MART', 'NBA_PROJECT', 'PLAYER_ORIENTED', 'SEASON', 'STAR_SCHEMA']
  )
}}


WITH RAW AS (

    SELECT 
        * 
    FROM {{ ref('MT_SEASON_PLAYER_STATS_WITH_DRAFT_DENORM') }}

),

GROUPING_CLAUSE as (

    SELECT
        PLAYER_FULL_NAME as PLAYER_FULL_NAME,
        PLAYER_BIRTH_DATE as PLAYER_BIRTH_DATE,
        PLAYER_SCHOOL as PLAYER_SCHOOL,
        PLAYER_COUNTRY as PLAYER_COUNTRY,
        PLAYER_PREVIOUS_TEAM as PLAYER_PREVIOUS_TEAM,
        PLAYER_PREVIOUS_TEAM_COUNTRY as PLAYER_PREVIOUS_TEAM_COUNTRY,
        PLAYER_DRAFT_YEAR as PLAYER_DRAFT_YEAR,
        PLAYER_DRAFT_NUMBER as PLAYER_DRAFT_NUMBER,
        PLAYER_IS_GREATEST_75 as PLAYER_IS_GREATEST_75,
        PLAYER_HEIGHT_IN_CM,
        PLAYER_WEIGHT_IN_KG, 
        PLAYER_MAIN_POSITION, 
        PLAYER_SECOND_POSITION,
        PLAYED_IN_DLEAGUE,
        PLAYER_SEASON_EXPERIENCE,
        MAX(IS_MVP) AS IS_MVP,
        MAX(IS_ROTY) AS IS_ROTY,
        MAX(IS_DPOY) AS IS_DPOY,
        MAX(IS_SIXTH_MAN) AS IS_SIXTH_MAN,
        MAX(IS_MIP) AS IS_MIP
        
    FROM RAW
    GROUP BY 
        PLAYER_FULL_NAME,
        PLAYER_BIRTH_DATE,
        PLAYER_SCHOOL,
        PLAYER_COUNTRY,
        PLAYER_PREVIOUS_TEAM,
        PLAYER_PREVIOUS_TEAM_COUNTRY,
        PLAYER_DRAFT_YEAR,
        PLAYER_DRAFT_NUMBER,
        PLAYER_IS_GREATEST_75,
        PLAYER_HEIGHT_IN_CM,
        PLAYER_WEIGHT_IN_KG, 
        PLAYER_MAIN_POSITION, 
        PLAYER_SECOND_POSITION,
        PLAYED_IN_DLEAGUE,
        PLAYER_SEASON_EXPERIENCE
),

DIM_PLAYER AS (
SELECT  
    {{ dbt_utils.generate_surrogate_key(['PLAYER_FULL_NAME', 'PLAYER_BIRTH_DATE']) }} as PLAYER_ID,
    * 
    , TO_TIMESTAMP(CURRENT_TIMESTAMP ) AS LOAD_DATE
    , 'NBA_DB.CORE_NBA_DATA.MT_SEASON_PLAYER_STATS_WITH_DRAFT_DENORM' AS SOURCE_TABLE
from GROUPING_CLAUSE
)

SELECT 
    *
FROM DIM_PLAYER