{{
  config(
    materialized = "table",
    tags = ["STAR_SCHEMA"]
  )
}}

WITH RAW AS (

    SELECT *
    FROM {{ ref('MT_SEASON_PLAYER_STATS_WITH_DRAFT_NORMALIZED') }}

),

STAR_SCHEMA AS (
SELECT 
    {{ dbt_utils.generate_surrogate_key(['PLAYER_FULL_NAME', 'PLAYER_BIRTH_DATE']) }} as PLAYER_ID
    , {{ dbt_utils.generate_surrogate_key(['PLAYER_SEASON_PLAYED']) }} as SEASON_ID
    , {{ dbt_utils.generate_surrogate_key(['TEAM_NAME']) }} as TEAM_ID
    , datediff(year, cast(PLAYER_BIRTH_DATE as date), cast(left(PLAYER_SEASON_PLAYED, 4) || '-07-01' as date)) as PLAYER_AGE
    , PLAYER_GAMES_PLAYED
    , PLAYER_GAMES_STARTED
    , PLAYER_MINUTES_PLAYED
    , PLAYER_FG_MADE
    , PLAYER_FG_ATTEMPTED
    , PLAYER_FG_PCT
    , PLAYER_3PT_MADE
    , PLAYER_3PT_ATTEMPTED
    , PLAYER_3PT_PCT
    , PLAYER_FT_MADE
    , PLAYER_FT_ATTEMMPTED
    , PLAYER_FT_PCT
    , PLAYER_OFF_REB
    , PLAYER_DEF_REB
    , PLAYER_TOT_REB
    , PLAYER_ASSISTS
    , PLAYER_STEALS
    , PLAYER_BLOCKS
    , PLAYER_TOVERS
    , PLAYER_FOULS
    , PLAYER_POINTS
    , PLAYER_FG_MADE_AVG
    , PLAYER_FG_ATTEMPTED_AVG
    , PLAYER_FG_PCT_AVG
    , PLAYER_3PT_MADE_AVG
    , PLAYER_3PT_ATTEMPTEDE_AVG
    , PLAYER_3PT_PCT_AVG
    , PLAYER_FT_MADE_AVG
    , PLAYER_FT_ATTEMMPTED_AVG
    , PLAYER_FT_PCT_AVG
    , PLAYER_OFF_REB_AVG
    , PLAYER_DEF_REB_AVG
    , PLAYER_TOT_REB_AVG
    , PLAYER_ASSISTS_AVG
    , PLAYER_STEALS_AVG
    , PLAYER_BLOCKS_AVG
    , PLAYER_TOVERS_AVG
    , PLAYER_FOULS_AVG
    , PLAYER_POINTS_AVG
    , TS_PCT
    , EFG_PCT
    , TOV_PCT
    , FTR
    , THREEPAR
    , ORB_PCT_EST
    , DRB_PCT_EST
    , AST_TOV_RATIO
    , TO_TIMESTAMP(CURRENT_TIMESTAMP ) AS LOAD_DATE
    , 'NBA_DB.CORE_NBA_DATA.MT_SEASON_PLAYER_STATS_WITH_DRAFT_NORMALIZED' AS SOURCE_TABLE
FROM RAW
)

SELECT *  FROM STAR_SCHEMA