version: 2

sources:
  - name: STAGING_NBA_DATA
    schema: STAGING_NBA_DATA
    tables:
      - name: STG_SEASON_PLAYER_STATS_V1
        description: "Dane z sezonu regularnego od sezonu 2010 do sezonu 2024 - część 1"
      - name: STG_SEASON_PLAYER_STATS_V2
        description: "Dane z sezonu regularnego od sezonu 2010 do sezonu 2024 - część 2"
      - name: STG_SEASON_PLAYER_STATS_V3
        description: "Dane z sezonu regularnego od sezonu 2010 do sezonu 2024 - część 3"
      - name: STG_SEASON_PLAYER_STATS
        description: "Dane z sezonu regularnego od sezonu 2010 do sezonu 2024 - połączone V1, V2, V3"
      - name: STG_SEASON_TEAM_STATS
        description: "Dane drużyn z sezonów regularnych od 2010 do 2024"
      - name: STG_PLAYOFFS_PLAYER_STATS
        description: "Dane zawodników z Playoffs od sezonu 2010 do sezonu 2024"
      - name: STG_PLAYOFFS_TEAM_STATS
        description: "Dane drużyn z Playoffs od sezonu 2010 do 2024"
      - name: STG_DRAFT_PLAYER_STATS
        description: "Dane z draftów od roku 2010"