version: 2

sources:
  - name: STAGING_NBA_DATA
    schema: STAGING_NBA_DATA
    tables:
      - name: STG_REG_SEASON24_API
        description: "Surowe dane meczów NBA wczytane do Snowflake"
      - name: STG_REG_SEASON_TOTALS
        description: "Dane od sezonu 2010 do sezonu 2024"
      - name: STG_PLAYOFFS_STATS
        description: "Dane z Playoffs od sezonu 2010 do sezonu 2024"
      - name: STG_REG_SEASON_STATS_V1
        description: "Dane z sezonu regularnego od sezonu 2010 do sezonu 2024 - część 1"
      - name: STG_REG_SEASON_STATS_V2
        description: "Dane z sezonu regularnego od sezonu 2010 do sezonu 2024 - część 2"
      - name: STG_REG_SEASON_STATS_V3
        description: "Dane z sezonu regularnego od sezonu 2010 do sezonu 2024 - część 3"
      - name: STG_REG_SEASON_STATS_ALL
        description: "Dane z sezonu regularnego od sezonu 2010 do sezonu 2024 - połączone V1, V2, V3"
      - name: STG_NBA_DRAFT_DATA
        description: "Dane z draftów od roku 2010"