version: 2

sources:
  - name: STAGING_NBA_DATA
    schema: STAGING_NBA_DATA
    tables:
      - name: STG_SEASON_PLAYER_STATS_V1
        description: "Dane z sezonu regularnego od sezonu 2010 do sezonu 2024 - część 1"
      - name: STG_SEASON_PLAYER_STATS_V2
        description: "Dane z sezonu regularnego od sezonu 2010 do sezonu 2024 - część 2"
      - name: STG_SEASON_PLAYER_STATS_V3
        description: "Dane z sezonu regularnego od sezonu 2010 do sezonu 2024 - część 3"
      - name: STG_SEASON_PLAYER_STATS
        description: "Dane z sezonu regularnego od sezonu 2010 do sezonu 2024 - połączone V1, V2, V3"
      - name: STG_SEASON_TEAM_STATS
        description: "Dane drużyn z sezonów regularnych od 2010 do 2024"
      - name: STG_PLAYOFFS_PLAYER_STATS
        description: "Dane zawodników z Playoffs od sezonu 2010 do sezonu 2024"
      - name: STG_PLAYOFFS_TEAM_STATS
        description: "Dane drużyn z Playoffs od sezonu 2010 do 2024"
      - name: STG_DRAFT_PLAYER_STATS
        description: "Dane z draftów od roku 2010"
      - name: STG_ALL_COMMON_PLAYER_INFO
        description: "Dane dotyczące zawodników. Zawiera całą historię zawodników"
      - name: STG_ALL_PLAYER_DETAILINFO
        description: "Tabela podobna co COMMON_PLAYER_INFO tylko, że z mniejszą ilością informacji. "
      - name: STG_ALL_TEAM_ARENA_ATTENDANCE
        description: "Tabela dotycząca zespołów z ilością widzów na danym meczu"
      - name: STG_ALL_TEAM_SCORELINE
        description: "Tabela z wynikami meczów o 1946 do 2024 roku"
      - name: STG_DRAFT_PLAYER_COMBINE_STATS
        description: "Tabela z wynikami z DRAFT COMBINE"
      - name: STG_DRAFT_PLAYER_HISTORY
        description: "Historia draftowa, bardzo szczegółowa."
      - name: STG_SEASON_TEAM_DETAILS
        description: "Bardzo detaliczne wiadomości o zespołach"
      - name: STG_SEASON_TEAM_GAMES_ALL
        description: "Dane na poziomie zespołów, zawierają wszystkie mecze od 1946 do 2025 z podziałem na playffs i regular season"
      - name: STG_SEASON_TEAM_HISTORY
        description: "Dane historyczne, aktywne zespoły do 2019 roku, info o nieaktywnych."
      - name: STG_SEASON_TEAM_NAMES
        description: "Dane dotyczące zespołów. Zawiera podstawowe informacje oraz rok założenia."
      - name: STG_SEASON_TEAM_SUMMARY2425
        description: "Sumaryczne statystyki na sezon 24-25 z basketball reference. Jako dodatek"
      - name: STG_SEASON_PLAYER_DATASET
        description: "Dane obejmujące całą historie wraz z statystykami per sezon"
      - name: STG_SEASON_PLAYER_AWARDS
        description: "Dane obejmujące wszystkie najważniejsze nagrody indywidualne zawodników"
      - name: STG_ALL_COMMON_PLAYER_INFO_2324_EXTENDED
        description: "Dane draftowe obejmujące zawodników z lat 2023 oraz 2024"
      - name: STG_ALL_COMMON_PLAYER_INFO_REST_PLAYER_PACKAGE
        description: "Dane dogrywane dla pozostałych zawodników. Uzyskane przez skrypt Pythona."