WITH CTE AS (
SELECT 
    *
FROM {{ ref('MT_SEASON_PLAYER_STATS_WITH_DRAFT') }}
)

SELECT 
    PLAYER_FULL_NAME
    , PLAYER_BIRTH_DATE
    , PLAYER_SEASON_PLAYED
    , INITCAP(PLAYER_SCHOOL) AS PLAYER_SCHOOL
    , CASE
        WHEN PLAYER_COUNTRY = 'USA' THEN 'USA'
        ELSE INITCAP(PLAYER_COUNTRY)
    END AS PLAYER_COUNTRY
    , INITCAP(PLAYER_PREVIOUS_TEAM) AS PLAYER_PREVIOUS_TEAM
    , CASE
        WHEN PLAYER_PREVIOUS_TEAM_COUNTRY = 'USA' THEN 'USA'
        ELSE INITCAP(PLAYER_PREVIOUS_TEAM_COUNTRY)
    END AS PLAYER_PREVIOUS_TEAM_COUNTRY
    , PLAYER_DRAFT_YEAR
    , PLAYER_DRAFT_NUMBER
    , CASE
        WHEN PLAYER_FULL_NAME IN ('Ray Allen','Dave Bing','Patrick Ewing','Hal Greer','Sam Jones','Jerry Lucas','Pete Maravich','Reggie Miller','Earl Monroe','Russell Westbrook','Bill Walton','Dwyane Wade') THEN TRUE
        ELSE PLAYER_IS_GREATEST_75
        END AS PLAYER_IS_GREATEST_75
    , SEASON_START_YEAR
    , SEASON_END_YEAR
    , PLAYER_HEIGHT_IN_CM
    , PLAYER_WEIGHT_IN_KG
    , CAST(PLAYER_SEASON_EXPERIENCE AS NUMBER) AS PLAYER_SEASON_EXPERIENCE
    , CASE
        WHEN INITCAP(PLAYER_MAIN_POSITION) = 'C' THEN 'Center'
        WHEN INITCAP(PLAYER_MAIN_POSITION) = 'G' THEN 'Guard'
        WHEN INITCAP(PLAYER_MAIN_POSITION) = 'F' THEN 'Forward'
        WHEN INITCAP(PLAYER_MAIN_POSITION) = 'Forward-Guard' THEN 'Guard-Forward'
        WHEN INITCAP(PLAYER_MAIN_POSITION) = 'Center-Forward' THEN 'Forward-Center'
        ELSE INITCAP(PLAYER_MAIN_POSITION)
    END AS PLAYER_MAIN_POSITION
    , INITCAP(PLAYER_SECOND_POSITION) AS PLAYER_SECOND_POSITION
    , INITCAP(PLAYER_ROSTER_STATUS) AS PLAYER_ROSTER_STATUS
    , PLAYED_IN_DLEAGUE
    , IS_MVP
    , IS_ROTY
    , IS_DPOY
    , IS_SIXTH_MAN
    , IS_MIP
    , NBA_3PT_ERA
    , NBA_ERA
    , TEAM_NAME
    , CASE
        WHEN TEAM_ABBREVIATION IN ('CHA','CHH') THEN 'CHA'
        WHEN TEAM_ABBREVIATION IN ('BAL','BLT') THEN 'BAL'
        WHEN TEAM_NAME = 'Unknown' THEN 'UKN'
        WHEN TEAM_ABBREVIATION IN ('GSW','GOS') THEN 'GSW'
        ELSE TEAM_ABBREVIATION
    END AS TEAM_ABBREVIATION
    , TEAM_CITY
    , TEAM_CONFERENCE
    , TEAM_DIVISION
    , TEAM_STATUS
    --, TEAM_FOUND_YEAR
    --, TEAM_TILL_YEAR
    , PLAYER_AGE
    , PLAYER_GAMES_PLAYED
    , PLAYER_GAMES_STARTED, PLAYER_MINUTES_PLAYED, PLAYER_FG_MADE, PLAYER_FG_ATTEMPTED, PLAYER_FG_PCT, PLAYER_3PT_MADE, PLAYER_3PT_ATTEMPTED
    , PLAYER_3PT_PCT, PLAYER_FT_MADE, PLAYER_FT_ATTEMMPTED, PLAYER_FT_PCT, PLAYER_OFF_REB, PLAYER_DEF_REB, PLAYER_TOT_REB, PLAYER_ASSISTS
    , PLAYER_STEALS, PLAYER_BLOCKS, PLAYER_TOVERS, PLAYER_FOULS, PLAYER_POINTS, PLAYER_FG_MADE_AVG, PLAYER_FG_ATTEMPTED_AVG, PLAYER_FG_PCT_AVG
    , PLAYER_3PT_MADE_AVG, PLAYER_3PT_ATTEMPTEDE_AVG, PLAYER_3PT_PCT_AVG, PLAYER_FT_MADE_AVG, PLAYER_FT_ATTEMMPTED_AVG, PLAYER_FT_PCT_AVG
    , PLAYER_OFF_REB_AVG, PLAYER_DEF_REB_AVG, PLAYER_TOT_REB_AVG, PLAYER_ASSISTS_AVG, PLAYER_STEALS_AVG, PLAYER_BLOCKS_AVG, PLAYER_TOVERS_AVG
    , PLAYER_FOULS_AVG, PLAYER_POINTS_AVG, TS_PCT, EFG_PCT, TOV_PCT, FTR, THREEPAR, ORB_PCT_EST, DRB_PCT_EST, AST_TOV_RATIO, LOAD_DATE, SOURCE_TABLE_1
 FROM CTE