with source as (
    select * 
    from {{ source('STAGING_NBA_DATA', 'STG_PLAYOFFS_PLAYER_STATS') }}
),

CLS_PLAYOFFS_PLAYER_STATS as (
    SELECT 
        CAST(PERSONID AS NUMBER) AS PLAYER_ID
        , CAST(GAMEID AS NUMBER) AS GAME_ID
        , CAST(TEAMID AS NUMBER) AS TEAM_ID
        , SEASON_YEAR
        , TO_DATE(GAME_DATE) AS GAME_DATE
        , CONCAT(TEAMCITY, ' ', TEAMNAME) AS TEAM_NAME
        , TEAMCITY AS TEAM_CITY
        , TEAMNAME AS TEAM_NICKNAME
        , TEAMTRICODE AS TEAM_ABBREVATION
        , PERSONNAME AS PLAYER_FULL_NAME
        , COALESCE(POSITION, 'Unknown') AS PLAYER_POSITION
        , COALESCE(COMMENT, 'Unknown') AS PLAYER_COMMENT
        , CASE 
            WHEN LEFT(MINUTES, 2) LIKE '%:%' THEN TO_NUMBER(LEFT(MINUTES,1))
            WHEN LEFT(MINUTES, 2) NOT LIKE '%:%' THEN TO_NUMBER(LEFT(MINUTES, 2))
        END AS PLAYER_MINUTES_PLAYED
        , TO_NUMBER(RIGHT(MINUTES, 2)) AS PLAYER_SECONDS_PLAYED
        , FIELDGOALSMADE AS PLAYER_FG_MADE
        , FIELDGOALSATTEMPTED AS  PLAYER_FG_ATTEMPTED
        , FIELDGOALSPERCENTAGE AS PLAYER_FG_PCT
        , THREEPOINTERSMADE AS PLAYER_3PT_MADE
        , THREEPOINTERSATTEMPTED AS PLAYER_3PT_ATTEMPTED
        , THREEPOINTERSPERCENTAGE AS PLAYER_3PT_PCT
        , FREETHROWSMADE AS PLAYER_FT_MADE
        , FREETHROWSATTEMPTED AS PLAYER_FT_ATTEMPTED
        , FREETHROWSPERCENTAGE AS PLAYER_FT_PCT
        , REBOUNDSOFFENSIVE AS PLAYER_OFF_REB
        , REBOUNDSDEFENSIVE AS PLAYER_DEF_REB
        , REBOUNDSTOTAL AS PLAYER_TOTAL_REB
        , ASSISTS AS PLAYER_AST
        , STEALS AS PLAYER_STL
        , BLOCKS AS PLAYER_BLK
        , TURNOVERS AS PLAYER_TOV
        , FOULSPERSONAL AS PLAYER_FOULS
        , POINTS AS PLAYER_PTS
        , PLUSMINUSPOINTS AS PLAYER_PLUS_MINUS
        , 1 AS IS_VALID
        , TO_TIMESTAMP(CURRENT_TIMESTAMP ) AS LOAD_DATE
        , 'STAGING_NBA_DATA.CLS_PLAYOFFS_PLAYER_STATS' AS SOURCE_TABLE
    from source
)

select * from CLS_PLAYOFFS_PLAYER_STATS
