with source as (
    select * 
    from {{ source('STAGING_NBA_DATA', 'STG_PLAYOFFS_TEAM_STATS') }}
),

CLS_PLAYOFFS_TEAM_STATS as (
    SELECT 
    SEASON_YEAR
    , TEAM_NAME
    , TEAM_ABBREVIATION
    , TO_DATE(GAME_DATE) AS GAME_DATE
    , MATCHUP AS TEAM_MATCHUP
    , WL AS GAME_RESULT
    , MIN AS TEAM_MINUTES_PLAYED
    , FGM AS TEAM_FG_MADE
    , FGA AS TEAM_FG_ATTEMPTED
    , FG_PCT AS TEAM_FG_PCT
    , FG3M AS TEAM_3PT_MADE
    , FG3A AS TEAM_3PT_ATTEMPTED
    , FG3_PCT AS TEAM_3PT_PCT
    , FTM AS TEAM_FT_MADE
    , FTA AS TEAM_FT_ATTEMPTE
    , FT_PCT AS TEAM_FT_PCT
    , OREB AS TEAM_OFF_REB
    , DREB AS TEAM_DEF_REB
    , REB AS TEAM_TOTAL_REB
    , AST AS TEAM_ASSISTS
    , TOV AS TEAM_TO
    , STL AS TEAM_STEALS
    , BLK AS TEAM_BLOCKS
    , PF AS TEAM_PERSONAL_FOULS
    , PTS AS TEAM_POINTS
    , 1 AS IS_VALID
    , TO_TIMESTAMP(CURRENT_TIMESTAMP ) AS LOAD_DATE
    , 'STAGING_NBA_DATA.STG_PLAYOFFS_TEAM_STATS' AS SOURCE_TABLE
    FROM source
)

select * from CLS_PLAYOFFS_TEAM_STATS
