WITH STAGING_NBA_DRAFT_DATA AS (
    SELECT * 
    FROM {{ source('STAGING_NBA_DATA', 'STG_DRAFT_PLAYER_STATS') }}
),

CLS_NBA_DRAFT_DATA AS (
    SELECT
    SUBSTR(ID, 2, 5) AS PLAYER_ID
    , CAST(TRIM(REPLACE("DraftYear", '"', ' ')) AS NUMBER) AS DRAFT_YEAR
    , CAST("Rk" AS NUMBER) AS DRAFT_NUMBER
    , TRIM(REPLACE("Player", '""', ' ')) AS PLAYER_NAME
    , TRIM(REPLACE("College", '""', ' ')) AS COLLEGE_NAME
    , SUBSTR("Tm", 3, 3) AS TEAM_ABREVIATION
    , CASE
        WHEN "Yrs" = 'NA' THEN NULL
        ELSE CAST("Yrs" AS NUMBER)
    END AS YEARS_PLAYED
    , CASE
        WHEN G = 'NA' THEN NULL
        ELSE CAST(G AS NUMBER)
    END AS GAMES_PLAYED
    , CASE
        WHEN TOTMP = 'NA' THEN NULL
        ELSE CAST(TOTMP AS NUMBER)
    END AS TOTAL_MINUTES_PLAYED
    , CASE
        WHEN TOTPTS = 'NA' THEN NULL
        ELSE CAST(TOTPTS AS NUMBER)
    END AS TOTAL_POINTS
    , CASE
        WHEN TOTTRB = 'NA' THEN NULL
        ELSE CAST(TOTTRB AS NUMBER)
    END AS TOTAL_REBOUNDS
    , CASE
        WHEN TOTAST = 'NA' THEN NULL
        ELSE CAST(TOTAST AS NUMBER)
    END AS TOTAL_ASSISTS
    , CASE
        WHEN "FG%" = 'NA' THEN NULL
        ELSE CAST("FG%" AS FLOAT)
    END AS AVG_FG
    , CASE
        WHEN "3P%" = 'NA' THEN NULL
        ELSE CAST("3P%" AS FLOAT)
    END AS AVG_3PTM
    , CASE
        WHEN "FT%" = 'NA' THEN NULL
        ELSE CAST("FT%" AS FLOAT)
    END AS AVG_FT
    , CASE
        WHEN WS = 'NA' THEN NULL
        ELSE CAST(WS AS FLOAT)
    END AS WIN_SHARED
    , CASE
        WHEN BPM = 'NA' THEN NULL
        ELSE CAST(BPM AS FLOAT)
    END AS "BOX +/-"
    , CASE
        WHEN VORP = 'NA' THEN NULL
        ELSE CAST(VORP AS FLOAT)
    END AS VORP
    , CASE
        WHEN PPG = 'NA' THEN NULL
        ELSE CAST(PPG AS FLOAT)
    END AS POINTS_PER_GAME
    , CASE
        WHEN RPG = 'NA' THEN NULL
        ELSE CAST(RPG AS FLOAT)
    END AS REBOUNDS_PER_GAME
    , CASE
        WHEN APG = 'NA' THEN NULL
        ELSE CAST(APG AS FLOAT)
    END AS ASSISTS_PER_GAME
FROM STAGING_NBA_DRAFT_DATA
),

CLS_NBA_DRAFT_DATA_V2 AS (
SELECT 
    PLAYER_ID, DRAFT_YEAR, DRAFT_NUMBER, {{ normalize_name('PLAYER_NAME') }} AS PLAYER_NAME, COLLEGE_NAME, TEAM_ABREVIATION, YEARS_PLAYED, GAMES_PLAYED, TOTAL_MINUTES_PLAYED
    , TOTAL_POINTS, TOTAL_REBOUNDS, TOTAL_ASSISTS, AVG_FG, AVG_3PTM, AVG_FT, WIN_SHARED, "BOX +/-", VORP, POINTS_PER_GAME, REBOUNDS_PER_GAME
    , ASSISTS_PER_GAME
FROM CLS_NBA_DRAFT_DATA
)

SELECT * FROM CLS_NBA_DRAFT_DATA_V2