with source as (
    select * 
    from {{ source('STAGING_NBA_DATA', 'STG_ALL_COMMON_PLAYER_INFO_REST_PLAYER_PACKAGE') }}
),

CLS_ALL_COMMON_PLAYER_INFO_REST_PLAYER_PACKAGE as (

SELECT 
    SPLIT_PART(PLAYER_NAME, ' ', 1) AS PLAYER_FIRST_NAME
    , SPLIT_PART(PLAYER_NAME, ' ', 2) PLAYER_LAST_NAME
    , PLAYER_NAME as PLAYER_FULL_NAME
    , CAST(BIRTH_DATE AS DATE) AS PLAYER_BIRTH_DATE
    , 'UNKNOWN' AS PLAYER_SCHOOL
    , COUNTRY AS PLAYER_COUNTRY
    , 'UNKNOWN' AS PLAYER_PREVIOUS_TEAM
    , 'UNKNOWN' AS PLAYER_PREVIOUS_TEAM_COUNTRY
    , CASE 
        WHEN HEIGHT IS NULL THEN NULL
        ELSE
        ROUND(CAST(SPLIT(HEIGHT, '-')[0] AS INTEGER) * 30.48 +
        CAST(SPLIT(HEIGHT, '-')[1] AS INTEGER) * 2.54, 1)
    END AS PLAYER_HEIGHT_IN_CM
    , CASE 
        WHEN WEIGHT IS NULL THEN NULL
        ELSE
        ROUND(CAST(WEIGHT AS INTEGER) * 0.45, 1)
    END AS PLAYER_WEIGHT_IN_KG
    , NULL AS PLAYER_SEASON_EXPERIENCE
    , POSITION AS PLAYER_MAIN_POSITION
    , 'UNKNOWN' AS PLAYER_SECOND_POSITION
    , 'UNKNOWN' AS PLAYER_ROSTER_STATUS
    , CONCAT(TEAM_CITY, ' ', TEAM) AS TEAM_NAME
    , TEAM_ABBREVIATION
    , TEAM AS TEAM_NICKNAME
    , TEAM_CITY
    , NULL AS TEAM_FOUND_YEAR
    , NULL AS TEAM_TILL_YEAR
    , NULL AS PLAYED_IN_DLEAGUE
    , DRAFT_YEAR
    , null AS DRAFT_ROUND
    , PICK_NUMBER AS DRAFT_NUMBER
    , NULL AS IS_GREATEST_75
    , TO_TIMESTAMP(CURRENT_TIMESTAMP ) AS LOAD_DATE
    , 'NBA_DB.CLEANSE_NBA_DATA.STG_ALL_COMMON_PLAYER_INFO_REST_PLAYER_PACKAGE' AS SOURCE_TABLE
    from source
)


SELECT * FROM CLS_ALL_COMMON_PLAYER_INFO_REST_PLAYER_PACKAGE