with source as (
    select * 
    from {{ source('STAGING_NBA_DATA', 'STG_SEASON_TEAM_GAMES_ALL') }}
),

CLS_SEASON_TEAM_GAMES_ALL as (
    SELECT 
        GAMEDATE AS MATCH_DATE
        , CONCAT(HOMETEAMCITY, ' ', HOMETEAMNAME) AS TEAM_NAME_HOME
        , HOMETEAMNAME AS TEAM_NICKNAME_HOME
        , HOMETEAMCITY AS TEAM_CITY_HOME
        , CONCAT(AWAYTEAMCITY, ' ', AWAYTEAMNAME) AS TEAM_NAME_AWAY
        , AWAYTEAMNAME AS TEAM_NICKNAME_AWAY
        , AWAYTEAMCITY AS TEAM_CITY_AWAY
        , HOMESCORE AS TEAM_PTS_HOME
        , AWAYSCORE AS TEAM_PTS_AWAY
        , CASE
            WHEN HOMESCORE > AWAYSCORE THEN CONCAT(HOMETEAMCITY, ' ', HOMETEAMNAME)
            WHEN HOMESCORE < AWAYSCORE THEN CONCAT(AWAYTEAMCITY, ' ', AWAYTEAMNAME)
            ELSE NULL
        END AS MATCH_WINNER
        , GAMETYPE AS MATCH_TYPE
        , ATTENDANCE AS MATCH_ATTENDANCE
        , ARENAID AS ARENA_ID
        , GAMELABEL AS MATCH_LABEL
        , GAMESUBLABEL AS MATCH_SUBLABEL
        , 1 AS IS_VALID
        , TO_TIMESTAMP(CURRENT_TIMESTAMP ) AS LOAD_DATE
        , 'STAGING_NBA_DATA.STG_SEASON_TEAM_GAMES_ALL' AS SOURCE_TABLE
    from source
)

select * from CLS_SEASON_TEAM_GAMES_ALL