with source as (
    select * 
    from {{ source('STAGING_NBA_DATA', 'STG_ALL_COMMON_PLAYER_INFO_2324_EXTENDED') }}
),

CLS_ALL_COMMON_PLAYER_INFO_2324_EXTENDED as (
 SELECT 
    INITCAP(TRIM({{ normalize_name('PLAYER_NAME') }})) AS PLAYER_FULL_NAME
    , DRAFT_YEAR AS DRAFT_YEAR
    , PICK_NUMBER AS DRAFT_NUMBER
    , COLLEGE AS PLAYER_PREVIOUS_TEAM
    , TEAM AS TEAM_NAME
    , TEAM_ABBREVIATION
    , TEAM_CITY
    , POSITION AS PLAYER_MAIN_POSITION
    , CASE 
        WHEN HEIGHT IS NULL THEN NULL
        ELSE
        ROUND(CAST(SPLIT(HEIGHT, '-')[0] AS INTEGER) * 30.48 +
        CAST(SPLIT(HEIGHT, '-')[1] AS INTEGER) * 2.54, 1)
    END AS PLAYER_HEIGHT_IN_CM
    , CASE 
        WHEN WEIGHT IS NULL THEN NULL
        ELSE
        ROUND(CAST(WEIGHT AS INTEGER) * 0.45, 1)
    END AS PLAYER_WEIGHT_IN_KG
    , BIRTH_DATE AS PLAYER_BIRTH_DATE
    , COUNTRY AS PLAYER_COUNTRY
    , 1 AS IS_VALID
    , TO_TIMESTAMP(CURRENT_TIMESTAMP ) AS LOAD_DATE
    , 'STAGING_NBA_DATA.STG_ALL_COMMON_PLAYER_INFO_2324_EXTENDED' AS SOURCE_TABLE
    from source
)


SELECT * FROM CLS_ALL_COMMON_PLAYER_INFO_2324_EXTENDED