with source as (
    select * 
    from {{ source('STAGING_NBA_DATA', 'STG_SEASON_TEAM_NAMES') }}
),

CLS_SEASON_TEAM_NAMES as (
    SELECT 
        ID AS TEAM_ID
        , FULL_NAME AS TEAM_NAME
        , ABBREVIATION AS TEAM_ABBREVIATION
        , NICKNAME AS TEAM_NICKNAME
        , CITY AS TEAM_CITY
        , STATE AS TEAM_STATE
        , CAST(YEAR_FOUNDED AS NUMBER) AS TEAM_FOUND_YEAR
        , 1 AS IS_VALID
        , TO_TIMESTAMP(CURRENT_TIMESTAMP ) AS LOAD_DATE
        , 'STAGING_NBA_DATA.STG_SEASON_TEAM_NAMES' AS SOURCE_TABLE
    from source
)

select * from CLS_SEASON_TEAM_NAMES