with CLS_SEASON_PLAYER_STATS as (
    select *, 'SEASON_GAME' AS GAME_TYPE
    from {{ ref('CLS_SEASON_PLAYER_STATS') }}
),

CLS_PLAYOFFS_PLAYER_STATS as (
    select *, 'PLAYOFFS_GAME' AS GAME_TYPE
    from {{ ref('CLS_PLAYOFFS_PLAYER_STATS') }}
)

select * from CLS_SEASON_PLAYER_STATS
UNION ALL
SELECT * FROM CLS_PLAYOFFS_PLAYER_STATS