with source as (
    select * 
    from {{ source('STAGING_NBA_DATA', 'STG_ALL_PLAYER_DETAILINFO') }}
),

CLS_ALL_PLAYER_DETAILINFO as (
    SELECT 
     INITCAP(TRIM(FIRSTNAME)) AS PLAYER_FIRST_NAME
     , INITCAP(TRIM(LASTNAME)) AS PLAYER_LAST_NAME
     , CONCAT(FIRSTNAME, ' ', LASTNAME) AS PLAYER_FULL_NAME 
     , TO_DATE(BIRTHDATE) AS PLAYER_BIRTH_DATE
     , COALESCE(LASTATTENDED, 'Uknonwn') AS PLAYER_SCHOOL
     , COALESCE(REPLACE(DRAFTYEAR, '-1.0' ,'Undrafted'), 'Undrafted') AS DRAFT_YEAR
     , COALESCE(REPLACE(DRAFTROUND, '-1.0' ,'Undrafted'), 'Undrafted') AS DRAFT_ROUND
     , COALESCE(REPLACE(DRAFTNUMBER, '-1.0' ,'Undrafted'), 'Undrafted') AS DRAFT_NUMBER
     , 1 AS IS_VALID
     , TO_TIMESTAMP(CURRENT_TIMESTAMP ) AS LOAD_DATE
    , 'STAGING_NBA_DATA.STG_ALL_PLAYER_DETAILINFO' AS SOURCE_TABLE
    from source
)

select * from CLS_ALL_PLAYER_DETAILINFO