with source as (
    select * 
    from {{ source('STAGING_NBA_DATA', 'STG_ALL_TEAM_SCORELINE') }}
),

CLS_ALL_TEAM_SCORELINE as (
    SELECT 
        TO_DATE(GAME_DATE_EST) AS MATCH_DATE
        , CASE
            WHEN TEAM_CITY_NAME_HOME = 'LA' THEN CONCAT('Los Angeles', ' ', TEAM_NICKNAME_HOME)
            ELSE CONCAT(TEAM_CITY_NAME_HOME, ' ', TEAM_NICKNAME_HOME)
        END AS TEAM_NAME_HOME
        , TEAM_ABBREVIATION_HOME
        , TEAM_NICKNAME_HOME
        , CASE
            WHEN TEAM_CITY_NAME_HOME = 'LA' THEN 'Los Angeles'
            ELSE TEAM_CITY_NAME_HOME
        END AS TEAM_CITY_HOME
        , CASE
            WHEN TEAM_CITY_NAME_AWAY = 'LA' THEN CONCAT('Los Angeles', ' ', TEAM_NICKNAME_AWAY)
            ELSE CONCAT(TEAM_CITY_NAME_AWAY, ' ', TEAM_NICKNAME_AWAY)
        END AS TEAM_NAME_AWAY
        , TEAM_ABBREVIATION_AWAY
        , TEAM_NICKNAME_AWAY    
        , CASE
            WHEN TEAM_CITY_NAME_AWAY = 'LA' THEN 'Los Angeles'
            ELSE TEAM_CITY_NAME_AWAY
        END AS TEAM_CITY_AWAY
        , CAST(PTS_QTR1_HOME AS NUMBER) AS TEAM_PTS_QTR1_HOME
        , CAST(PTS_QTR2_HOME AS NUMBER) AS TEAM_PTS_QTR2_HOME
        , CAST(PTS_QTR3_HOME AS NUMBER) AS TEAM_PTS_QTR3_HOME
        , CAST(PTS_QTR4_HOME AS NUMBER) AS TEAM_PTS_QTR4_HOME
        , CAST(PTS_OT1_HOME AS NUMBER) AS TEAM_PTS_OT1_HOME
        , CAST(PTS_OT2_HOME AS NUMBER) AS TEAM_PTS_OT2_HOME
        , CAST(PTS_OT3_HOME AS NUMBER) AS TEAM_PTS_OT3_HOME
        , CAST(PTS_OT4_HOME AS NUMBER) AS TEAM_PTS_OT4_HOME
        , CAST(PTS_OT5_HOME AS NUMBER) AS TEAM_PTS_OT5_HOME
        , CAST(PTS_QTR1_HOME + PTS_QTR2_HOME + PTS_QTR3_HOME + PTS_QTR4_HOME AS NUMBER) AS TEAM_REGULAR_TIME_PTS_HOME
        , CAST(PTS_HOME AS NUMBER) AS TEAM_PTS_HOME
        , CAST(PTS_QTR1_AWAY AS NUMBER) AS TEAM_PTS_QTR1_AWAY
        , CAST(PTS_QTR2_AWAY AS NUMBER) AS TEAM_PTS_QTR2_AWAY
        , CAST(PTS_QTR3_AWAY AS NUMBER) AS TEAM_PTS_QTR3_AWAY
        , CAST(PTS_QTR4_AWAY AS NUMBER) AS TEAM_PTS_QTR4_AWAY
        , CAST(PTS_OT1_AWAY AS NUMBER) AS TEAM_PTS_OT1_AWAY
        , CAST(PTS_OT2_AWAY AS NUMBER) AS TEAM_PTS_OT2_AWAY
        , CAST(PTS_OT3_AWAY AS NUMBER) AS TEAM_PTS_OT3_AWAY
        , CAST(PTS_OT4_AWAY AS NUMBER) AS TEAM_PTS_OT4_AWAY
        , CAST(PTS_OT5_AWAY AS NUMBER) AS TEAM_PTS_OT5_AWAY
        , CAST(PTS_QTR1_AWAY + PTS_QTR2_AWAY + PTS_QTR3_AWAY + PTS_QTR4_AWAY AS NUMBER) AS TEAM_REGULAR_TIME_PTS_AWAY
        , CAST(PTS_AWAY AS NUMBER) AS TEAM_PTS_AWAY
        , CASE 
            WHEN PTS_OT1_HOME IS NULL OR PTS_OT1_AWAY IS NULL OR PTS_OT1_HOME = 0 OR PTS_OT1_AWAY = 0  THEN 'Without OT'
            WHEN PTS_OT1_HOME IS NOT NULL OR PTS_OT1_AWAY IS NOT NULL OR PTS_OT1_HOME <> 0 OR PTS_OT1_AWAY <> 0 THEN 'OT'
        ELSE NULL
        END AS IS_OVERTIME
        , 1 AS IS_VALID
        , TO_TIMESTAMP(CURRENT_TIMESTAMP ) AS LOAD_DATE
        , 'STAGING_NBA_DATA.STG_ALL_TEAM_SCORELINE' AS SOURCE_TABLE
    from source
)

select * from CLS_ALL_TEAM_SCORELINE