with source as (
    select * 
    from {{ source('STAGING_NBA_DATA', 'STG_DRAFT_PLAYER_COMBINE_STATS') }}
),

CLS_DRAFT_PLAYER_COMBINE_STATS as (
    SELECT
        SEASON
        , INITCAP({{ normalize_name('PLAYER_NAME') }}) AS PLAYER_FULL_NAME
        , REPLACE(SPLIT(POSITION, '-')[0], '"', '') AS PLAYER_MAIN_POSITION
        , COALESCE(REPLACE(SPLIT(POSITION, '-')[1], '"', ''), 'None') AS PLAYER_SECOND_POSITION
        , ROUND(COALESCE(HEIGHT_W_SHOES, HEIGHT_WO_SHOES + 1.5) * 2.54,1) AS PLAYER_HEIGHT_IN_CM
        , CAST(WEIGHT * 0.45359237 AS NUMBER) AS PLAYER_WEIGHT_IN_KG
        , ROUND(WINGSPAN * 2.54,1) AS PLAYER_WINGSPAN_IN_CM
        , ROUND(STANDING_REACH * 2.54,1) AS PLAYER_STANDING_REACH_IN_CM
        , ROUND(BODY_FAT_PCT,1) AS PLAYER_BODY_FAT_PCT
        , ROUND(HAND_LENGTH * 2.54,1) AS PLAYER_HAND_LENGTH_IN_CM
        , ROUND(HAND_WIDTH * 2.54,1) AS PLAYER_HAND_WIDTH_IN_CM
        , ROUND(STANDING_VERTICAL_LEAP * 2.54,1) AS DRAFT_STANDING_VERTICAL_LEAP_IN_CM
        , ROUND(MAX_VERTICAL_LEAP * 2.54,1) AS DRAFT_MAX_VERTICAL_LEAP_IN_CM
        , LANE_AGILITY_TIME AS DRAFT_LANE_AGILITY_TIME
        , THREE_QUARTER_SPRINT AS DRAFT_THREE_QUARTER_SPRINT
        , CAST(BENCH_PRESS AS NUMBER) AS DRAFT_BENCH_PRESS_RESULT
        , ROUND((SPLIT(SPOT_FIFTEEN_CORNER_LEFT, '-')[0] + SPLIT(SPOT_FIFTEEN_BREAK_LEFT, '-')[0] + SPLIT(SPOT_FIFTEEN_TOP_KEY, '-')[0] + SPLIT(SPOT_FIFTEEN_BREAK_RIGHT, '-')[0] + SPLIT(SPOT_FIFTEEN_CORNER_RIGHT, '-')[0]) / 25, 1) AS DRAFT_SPOT_FIFTEEN_SUMMARY_PCT
        , ROUND((SPLIT(SPOT_COLLEGE_CORNER_LEFT, '-')[0] + SPLIT(SPOT_COLLEGE_BREAK_LEFT, '-')[0] + SPLIT(SPOT_COLLEGE_TOP_KEY, '-')[0] + SPLIT(SPOT_COLLEGE_BREAK_RIGHT, '-')[0] + SPLIT(SPOT_COLLEGE_CORNER_RIGHT, '-')[0]) / 25, 1) AS DRAFT_SPOT_COLLEGE_SUMMARY_PCT
        , ROUND((SPLIT(SPOT_NBA_CORNER_LEFT, '-')[0] + SPLIT(SPOT_NBA_BREAK_LEFT, '-')[0] + SPLIT(SPOT_NBA_TOP_KEY, '-')[0] + SPLIT(SPOT_NBA_BREAK_RIGHT, '-')[0] + SPLIT(SPOT_NBA_CORNER_RIGHT, '-')[0]) / 25, 1) AS DRAFT_SPOT_NBA_SUMMARY_PCT
        , ROUND((SPLIT(OFF_DRIB_FIFTEEN_BREAK_LEFT, '-')[0] + SPLIT(OFF_DRIB_FIFTEEN_TOP_KEY, '-')[0] + SPLIT(OFF_DRIB_FIFTEEN_BREAK_RIGHT, '-')[0]) / 15, 1) AS DRAFT_OFF_DRIB_FIFTEEN_SUMMARY_PCT
        , ROUND((SPLIT(OFF_DRIB_COLLEGE_BREAK_LEFT, '-')[0] + SPLIT(OFF_DRIB_COLLEGE_TOP_KEY, '-')[0] + SPLIT(OFF_DRIB_COLLEGE_BREAK_RIGHT, '-')[0]) / 15, 1) AS DRAFT_OFF_DRIB_COLLEGE_SUMMARY_PCT
        , CAST(REPLACE(SPLIT(ON_MOVE_FIFTEEN, '-')[0], '"', '') AS NUMBER) AS DRAFT_ON_MOVE_FIFTEEN_SHOT_MAD
        , CAST(REPLACE(SPLIT(ON_MOVE_FIFTEEN, '-')[1], '"', '') AS NUMBER) AS DRAFT_ON_MOVE_FIFTEEN_SHOT_ATT
        , CAST(REPLACE(SPLIT(ON_MOVE_FIFTEEN, '-')[0], '"', '') AS NUMBER) / CAST(REPLACE(SPLIT(ON_MOVE_FIFTEEN, '-')[1], '"', '') AS NUMBER) AS DRAFT_ON_MOVE_FIFTEEN_SUMMARY_PCT
        , CAST(REPLACE(SPLIT(ON_MOVE_COLLEGE, '-')[0], '"', '') AS NUMBER) AS DRAFT_ON_MOVE_COLLEGE_SHOT_MAD
        , CAST(REPLACE(SPLIT(ON_MOVE_COLLEGE, '-')[1], '"', '') AS NUMBER) AS DRAFT_ON_MOVE_COLLEGE_SHOT_ATT
        , CAST(REPLACE(SPLIT(ON_MOVE_COLLEGE, '-')[0], '"', '') AS NUMBER) / CAST(REPLACE(SPLIT(ON_MOVE_COLLEGE, '-')[1], '"', '') AS NUMBER) AS DRAFT_ON_MOVE_COLLEGE_SUMMARY_PCT
        , CASE
            WHEN REPLACE(SPLIT(POSITION, '-')[0], '"', '') IS NULL THEN 0
            ELSE 1
        END AS IS_VALID
        , TO_TIMESTAMP(CURRENT_TIMESTAMP ) AS LOAD_DATE
        , 'STAGING_NBA_DATA.STG_DRAFT_PLAYER_COMBINE_STATS' AS SOURCE_TABLE
    from source
)

select * from CLS_DRAFT_PLAYER_COMBINE_STATS