with source as (
    select * 
    from {{ source('STAGING_NBA_DATA', 'STG_ALL_COMMON_PLAYER_INFO') }}
),

CLS_ALL_COMMON_PLAYER_INFO as (
 SELECT --PERSON_ID, 
    INITCAP(TRIM(FIRST_NAME)) AS PLAYER_FIRST_NAME
    , INITCAP(TRIM(LAST_NAME)) AS PLAYER_LAST_NAME
    , INITCAP(TRIM(DISPLAY_FIRST_LAST)) AS PLAYER_FULL_NAME
    , TO_DATE(BIRTHDATE) AS PLAYER_BIRTH_DATE
    , COALESCE(SCHOOL, 'Uknonwn') AS PLAYER_SCHOOL
    , COALESCE(COUNTRY, 'Uknonwn') AS PLAYER_COUNTRY
    , REPLACE(SPLIT(LAST_AFFILIATION, '/')[0], '"','') AS PLAYER_PREVIOUS_TEAM
    , COALESCE(REPLACE(SPLIT(LAST_AFFILIATION, '/')[1], '"',''), 'Unknown') AS PLAYER_PREVIOUS_TEAM_COUNTRY
    , CASE 
        WHEN HEIGHT IS NULL THEN NULL
        ELSE
        ROUND(CAST(SPLIT(HEIGHT, '-')[0] AS INTEGER) * 30.48 +
        CAST(SPLIT(HEIGHT, '-')[1] AS INTEGER) * 2.54, 1)
    END AS PLAYER_HEIGHT_IN_CM
    , CASE 
        WHEN WEIGHT IS NULL THEN NULL
        ELSE
        ROUND(CAST(WEIGHT AS INTEGER) * 0.45, 1)
    END AS PLAYER_WEIGHT_IN_KG
    , CAST(SEASON_EXP AS INTEGER) AS PLAYER_SEASON_EXPERIENCE
    , COALESCE(SPLIT(POSITION, '-')[0], 'Unknown') AS PLAYER_MAIN_POSITION
    , COALESCE(SPLIT(POSITION, '-')[1], 'Unknown') AS PLAYER_SECOND_POSITION
    , ROSTERSTATUS AS PLAYER_ROSTER_STATUS
    , INITCAP(COALESCE(TEAM_NAME, 'Unknown')) AS TEAM_NAME
    , UPPER(COALESCE(TEAM_ABBREVIATION, 'Unknown')) AS TEAM_ABBREVIATION
    , INITCAP(COALESCE(TEAM_CODE, 'Unknown')) AS TEAM_NICKNAME
    , INITCAP(COALESCE(TEAM_CITY, 'Unknown')) AS TEAM_CITY
    , CAST(FROM_YEAR AS NUMBER) AS TEAM_FOUND_YEAR
    , CAST(TO_YEAR AS NUMBER) AS TEAM_TILL_YEAR
    , DLEAGUE_FLAG AS PLAYED_IN_DLEAGUE
    , DRAFT_YEAR 
    , COALESCE(DRAFT_ROUND, 'Undrafted') AS DRAFT_ROUND
    , COALESCE(DRAFT_NUMBER, 'Undrafted') AS DRAFT_NUMBER
    , GREATEST_75_FLAG AS IS_GREATEST_75
    , CASE
        WHEN HEIGHT IS NULL THEN 0
        WHEN WEIGHT IS NULL THEN 0
        WHEN FROM_YEAR IS NULL THEN 0
        WHEN TO_YEAR IS NULL THEN 0
        ELSE 1
    END AS IS_VALID
    , TO_TIMESTAMP(CURRENT_TIMESTAMP ) AS LOAD_DATE
    , 'STAGING_NBA_DATA.STG_ALL_COMMON_PLAYER_INFO' AS SOURCE_TABLE
    from source
)

select * from CLS_ALL_COMMON_PLAYER_INFO