with source as (
    select * 
    from {{ source('STAGING_NBA_DATA', 'STG_ALL_COMMON_PLAYER_INFO') }}
),

CLS_ALL_COMMON_PLAYER_INFO as (
 SELECT --PERSON_ID, 
    INITCAP(TRIM(FIRST_NAME)) AS PLAYER_FIRST_NAME
    , INITCAP(TRIM(LAST_NAME)) AS PLAYER_LAST_NAME
    , INITCAP(TRIM({{ normalize_name('DISPLAY_FIRST_LAST') }})) AS PLAYER_FULL_NAME
    , TO_DATE(BIRTHDATE) AS PLAYER_BIRTH_DATE
    , COALESCE(SCHOOL, 'Uknonwn') AS PLAYER_SCHOOL
    , COALESCE(COUNTRY, 'Uknonwn') AS PLAYER_COUNTRY
    , REPLACE(SPLIT(LAST_AFFILIATION, '/')[0], '"','') AS PLAYER_PREVIOUS_TEAM
    , COALESCE(REPLACE(SPLIT(LAST_AFFILIATION, '/')[1], '"',''), 'Unknown') AS PLAYER_PREVIOUS_TEAM_COUNTRY
    , CASE 
        WHEN HEIGHT IS NULL THEN NULL
        ELSE
        ROUND(CAST(SPLIT(HEIGHT, '-')[0] AS INTEGER) * 30.48 +
        CAST(SPLIT(HEIGHT, '-')[1] AS INTEGER) * 2.54, 1)
    END AS PLAYER_HEIGHT_IN_CM
    , CASE 
        WHEN WEIGHT IS NULL THEN NULL
        ELSE
        ROUND(CAST(WEIGHT AS INTEGER) * 0.45, 1)
    END AS PLAYER_WEIGHT_IN_KG
    , CAST(SEASON_EXP AS INTEGER) AS PLAYER_SEASON_EXPERIENCE
    , COALESCE(SPLIT(POSITION, '-')[0], 'Unknown') AS PLAYER_MAIN_POSITION
    , COALESCE(SPLIT(POSITION, '-')[1], 'Unknown') AS PLAYER_SECOND_POSITION
    , ROSTERSTATUS AS PLAYER_ROSTER_STATUS
    , INITCAP(CONCAT(COALESCE(TEAM_CITY, 'Unknown'), ' ', COALESCE(TEAM_NAME, 'Unknown'))) AS TEAM_NAME
    , UPPER(COALESCE(TEAM_ABBREVIATION, 'Unknown')) AS TEAM_ABBREVIATION
    , INITCAP(COALESCE(TEAM_CODE, 'Unknown')) AS TEAM_NICKNAME
    , INITCAP(COALESCE(TEAM_CITY, 'Unknown')) AS TEAM_CITY
    , CAST(FROM_YEAR AS NUMBER) AS TEAM_FOUND_YEAR
    , CAST(TO_YEAR AS NUMBER) AS TEAM_TILL_YEAR
    , DLEAGUE_FLAG AS PLAYED_IN_DLEAGUE
    , CASE
        WHEN  DISPLAY_FIRST_LAST = 'Mike James' AND BIRTHDATE like '%1975%' THEN '2001'
    ELSE DRAFT_YEAR
    END AS DRAFT_YEAR 
    , COALESCE(DRAFT_ROUND, 'Undrafted') AS DRAFT_ROUND
    , COALESCE(DRAFT_NUMBER, 'Undrafted') AS DRAFT_NUMBER
    , GREATEST_75_FLAG AS IS_GREATEST_75
    , CASE
        WHEN HEIGHT IS NULL THEN 0
        WHEN WEIGHT IS NULL THEN 0
        WHEN FROM_YEAR IS NULL THEN 0
        WHEN TO_YEAR IS NULL THEN 0
        ELSE 1
    END AS IS_VALID
    , TO_TIMESTAMP(CURRENT_TIMESTAMP ) AS LOAD_DATE
    , 'STAGING_NBA_DATA.STG_ALL_COMMON_PLAYER_INFO' AS SOURCE_TABLE
    from source
),

CTE AS (
SELECT 
    PLAYER_FULL_NAME
    , ROW_NUMBER() OVER (PARTITION BY PLAYER_FULL_NAME ORDER BY PLAYER_FULL_NAME) AS RN 
FROM CLS_ALL_COMMON_PLAYER_INFO
),

CTF AS (
SELECT DISTINCT(PLAYER_FULL_NAME) FROM CLS_ALL_COMMON_PLAYER_INFO
WHERE PLAYER_FULL_NAME IN (SELECT PLAYER_FULL_NAME FROM CTE WHERE RN > 1)
),

CTG AS (
SELECT 
    * 
    , 'Regular' IS_SAME_NAME
FROM CLS_ALL_COMMON_PLAYER_INFO
WHERE PLAYER_FULL_NAME NOT IN (SELECT * FROM CTF) 
),

CTH AS (
SELECT 
    * 
    , 'Other' IS_SAME_NAME
FROM CLS_ALL_COMMON_PLAYER_INFO
WHERE PLAYER_FULL_NAME IN (SELECT * FROM CTF) 
),

CTI AS (
    SELECT * FROM CTG
    UNION ALL
    SELECT * FROM CTH
),

CTII AS (
    SELECT 
    SPLIT_PART(PLAYER_FULL_NAME, ' ', 1) AS PLAYER_FIRST_NAME
    , SPLIT_PART(PLAYER_FULL_NAME, ' ', 2) AS PLAYER_LAST_NAME
    , PLAYER_FULL_NAME
    , PLAYER_BIRTH_DATE
    , PLAYER_PREVIOUS_TEAM AS PLAYER_SCHOOL
    , PLAYER_COUNTRY AS PLAYER_COUNTRY
    , PLAYER_PREVIOUS_TEAM
    , 'UNKNOWN' AS PLAYER_PREVIOUS_TEAM_COUNTRY
    , PLAYER_HEIGHT_IN_CM
    , PLAYER_WEIGHT_IN_KG
    , CASE
        WHEN DRAFT_YEAR = 2023 THEN 2
        WHEN DRAFT_YEAR = 2024 THEN 1
    ELSE 0
    END AS PLAYER_SEASON_EXPERIENCE
    , PLAYER_MAIN_POSITION
    , 'UNKNOWN' AS PLAYER_SECOND_POSITION
    , 'UNKNOWN' AS PLAYER_ROSTER_STATUS
    , TEAM_NAME
    , TEAM_ABBREVIATION
    , 'UNKNOWN' AS TEAM_NICKNAME
    , TEAM_CITY
    , NULL AS TEAM_FOUND_YEAR
    , NULL AS TEAM_TILL_YEAR
    , NULL AS PLAYED_IN_DLEAGUE
    , CAST (DRAFT_YEAR AS TEXT) AS DRAFT_YEAR
    , 'UNKNOWN' AS DRAFT_ROUND
    , CAST (DRAFT_NUMBER AS TEXT) AS DRAFT_NUMBER
    , 'NO' AS IS_GREATEST_75
    , 1 AS IS_VALID
    , TO_TIMESTAMP(CURRENT_TIMESTAMP ) AS LOAD_DATE
    , 'NBA_DB.CLEANSE_NBA_DATA.CLS_ALL_COMMON_PLAYER_INFO_2324' AS SOURCE_TABLE
    , 'Regular' AS IS_SAME_NAME
FROM {{ ref('CLS_ALL_COMMON_PLAYER_INFO_2324') }}
),

CTIII AS (
    SELECT 
        PLAYER_FIRST_NAME
        , PLAYER_LAST_NAME
        , INITCAP(TRIM({{ normalize_name('PLAYER_FULL_NAME') }})) AS PLAYER_FULL_NAME
        , PLAYER_BIRTH_DATE
        , PLAYER_SCHOOL
        , PLAYER_COUNTRY
        , PLAYER_PREVIOUS_TEAM
        , PLAYER_PREVIOUS_TEAM_COUNTRY
        , PLAYER_HEIGHT_IN_CM
        , PLAYER_WEIGHT_IN_KG
        , PLAYER_SEASON_EXPERIENCE
        , PLAYER_MAIN_POSITION
        , PLAYER_SECOND_POSITION
        , PLAYER_ROSTER_STATUS
        , TEAM_NAME
        , TEAM_ABBREVIATION
        , TEAM_NICKNAME
        , TEAM_CITY
        , TEAM_FOUND_YEAR
        , TEAM_TILL_YEAR
        , PLAYED_IN_DLEAGUE
        , DRAFT_YEAR
        , DRAFT_ROUND
        , DRAFT_NUMBER
        , IS_GREATEST_75
        , 1 AS IS_VALID
        , TO_TIMESTAMP(CURRENT_TIMESTAMP ) AS LOAD_DATE
        , 'NBA_DB.CLEANSE_NBA_DATA.CLS_ALL_COMMON_PLAYER_INFO_REST_PLAYER_PACKAGE' AS SOURCE_TABLE
        , 'Regular' AS IS_SAME_NAME
FROM {{ ref('CLS_ALL_COMMON_PLAYER_INFO_REST_PLAYER_PACKAGE') }}

)


SELECT * FROM CTI
UNION ALL
SELECT * FROM CTII
UNION ALL
SELECT * FROM CTIII