version: 2

models:
  - name: CLS_REG_SEASON24_API
    description: "Cleasingowa wersja tabeli stage'owej STG_REG_SEASON24_API z oczyszczonymi danymi"
    columns:
      - name: game_id
        tests:
          - not_null
          - unique
      - name: game_date
        tests:
          - not_null
      - name: home_team
        tests:
          - not_null
      - name: visitor_team
        tests:
          - not_null
  - name: cls_reg_season_totals
    description: >
      Oczyszczone dane ze statystyk drużyn NBA w sezonie regularnym.
      Dane pochodzą ze źródła STG_REG_SEASON_TOTALS i zostały poddane podstawowej transformacji:
      zmiana formatu daty, konwersje typów liczbowych oraz zmiana nazw kolumn na czytelne aliasy.
      Model zawiera metadane dotyczące daty ładowania danych (`load_date`).
    columns:
      - name: game_id
        description: Unikalny identyfikator meczu.
        tests: [not_null]
      - name: team_id
        description: Identyfikator drużyny.
        tests: [not_null]
      - name: game_date
        description: Data rozegrania meczu w formacie YYYY-MM-DD.
      - name: season_year
        description: Rok sezonu NBA.
      - name: team_name
        description: Nazwa drużyny.
      - name: team_abbreviation
        description: Skrót drużyny (np. LAL, BOS).
      - name: matchup
        description: Opis pojedynku, np. "LAL vs BOS".
      - name: wl
        description: Flaga zwycięstwa/przegranej (W/L).
      - name: game_length
        description: Liczba minut rozegranych przez zespół.
      - name: fg_made
        description: Celne rzuty z gry (Field Goals Made).
      - name: fg_attempted
        description: Próby rzutów z gry (Field Goals Attempted).
      - name: fg_pct
        description: Skuteczność rzutów z gry (FG%).
      - name: fg3_made
        description: Celne rzuty za 3 punkty.
      - name: fg3_attempted
        description: Próby rzutów za 3 punkty.
      - name: fg3_pct
        description: Skuteczność rzutów za 3 punkty (FG3%).
      - name: ft_made
        description: Celne rzuty wolne (Free Throws Made).
      - name: ft_attempted
        description: Próby rzutów wolnych.
      - name: ft_pct
        description: Skuteczność rzutów wolnych (FT%).
      - name: oreb
        description: Zbiórki ofensywne.
      - name: dreb
        description: Zbiórki defensywne.
      - name: reb
        description: Całkowita liczba zbiórek.
      - name: ast
        description: Asysty.
      - name: tov
        description: Straty (Turnovers).
      - name: stl
        description: Przechwyty.
      - name: blk
        description: Bloki.
      - name: pf
        description: Faule.
      - name: pts
        description: Punkty zdobyte.
      - name: plus_minus
        description: Wskaźnik +/- zawodnika (różnica punktowa podczas jego obecności na parkiecie).
      - name: load_date
        description: Data i czas załadowania danych do warstwy cleanse.
