version: 2

sources:
  - name: raw
    schema: STAGING_NBA_DATA
    tables:
      - name: STG_REG_SEASON24_API
        description: "Surowe dane meczów NBA wczytane do Snowflake"

models:
  - name: CLS_REG_SEASON24_API
    description: "Cleasingowa wersja tabeli stage'owej STG_REG_SEASON24_API z oczyszczonymi danymi"
    columns:
      - name: game_id
        tests:
          - not_null
          - unique
      - name: game_date
        tests:
          - not_null
      - name: home_team
        tests:
          - not_null
      - name: visitor_team
        tests:
          - not_null