WITH CTE AS (
    SELECT 
        * 
    FROM {{ ref('CLS_DRAFT_PLAYER_HISTORY') }}
),

CTF AS (
    SELECT 
        * 
    FROM {{ ref('CLS_DRAFT_PLAYER_STATS') }}
),

CTG AS (
SELECT 
    CASE 
        WHEN PLH.PLAYER_FULL_NAME IS NOT NULL THEN PLH.PLAYER_FULL_NAME
        ELSE PST.PLAYER_NAME
    END AS PLAYER_FULL_NAME
    , CASE
        WHEN PLH.DRAFT_YEAR IS NOT NULL THEN PLH.DRAFT_YEAR
        ELSE PST.DRAFT_YEAR
    END AS DRAFT_YEAR
    , CASE
        WHEN PLH.OVERALL_PICK IS NOT NULL THEN PLH.OVERALL_PICK
        ELSE PST.DRAFT_NUMBER
    END AS DRAFT_NUMBER
    , CASE
        WHEN PLH.DRAFT_TYPE IS NOT NULL THEN PLH.DRAFT_TYPE
        ELSE 'Unknown'
    END AS DRAFT_TYPE
    , CASE
        WHEN PLH.TEAM_NAME IS NOT NULL THEN PLH.TEAM_NAME
        ELSE PST.TEAM_ABREVIATION
    END AS TEAM_NAME
    , CASE
        WHEN PLH.TEAM_ABBREVIATION IS NOT NULL THEN PLH.TEAM_ABBREVIATION
        ELSE PST.TEAM_ABREVIATION
    END AS TEAM_ABBREVIATION
    , CASE
        WHEN PLH.TEAM_NICKNAME IS NOT NULL THEN PLH.TEAM_NICKNAME
        ELSE 'Unknown'
    END AS TEAM_NICKNAME
    , CASE
        WHEN PLH.TEAM_CITY IS NOT NULL THEN PLH.TEAM_CITY
        ELSE 'Unknown'
    END AS TEAM_CITY
    , CASE
        WHEN PLH.TEAM_ORGANIZTION IS NOT NULL THEN PLH.TEAM_ORGANIZTION
        ELSE PST.COLLEGE_NAME
    END AS COLLEGE_OR_TEAM_NAME
    , CASE
        WHEN PLH.TEAM_ORGANIZTION_TYPE IS NOT NULL THEN PLH.TEAM_ORGANIZTION_TYPE
        ELSE 'Unknown'
    END AS TEAM_ORGANIZTION_TYPE
    , PST.YEARS_PLAYED
    , PST.GAMES_PLAYED
    , PST.TOTAL_MINUTES_PLAYED
    , PST.TOTAL_POINTS
    , PST.TOTAL_REBOUNDS
    , PST.TOTAL_ASSISTS
    , PST.AVG_FG
    , PST.AVG_3PTM
    , PST.AVG_FT
    , PST.WIN_SHARED
    , PST."BOX +/-"
    , PST.VORP
    , PST.POINTS_PER_GAME
    , PST.REBOUNDS_PER_GAME
    , PST.ASSISTS_PER_GAME
    , 1 AS IS_VALID
     , TO_TIMESTAMP(CURRENT_TIMESTAMP ) AS LOAD_DATE
    , 'NBA_DB.CLEANSE_NBA_DATA.CLS_DRAFT_PLAYER_HISTORY' AS SOURCE_TABLE_1
    , 'NBA_DB.CLEANSE_NBA_DATA.CLS_DRAFT_PLAYER_STATS' AS SOURCE_TABLE_2
FROM CTE PLH
FULL JOIN CTF PST 
ON PST.DRAFT_YEAR = PLH.DRAFT_YEAR AND PST.DRAFT_NUMBER = PLH.OVERALL_PICK
)

SELECT * FROM CTG