WITH CTE AS (
    SELECT 
        * 
    FROM {{ ref('CLS_DRAFT_PLAYER_HISTORY') }}
),

CTF AS (
    SELECT 
        * 
    FROM {{ ref('CLS_DRAFT_PLAYER_STATS') }}
),

CTG AS (
SELECT 
    CASE 
        WHEN PLH.PLAYER_FULL_NAME IS NOT NULL THEN PLH.PLAYER_FULL_NAME
        ELSE PST.PLAYER_NAME
    END AS PLAYER_FULL_NAME
    , CASE
        WHEN PLH.DRAFT_YEAR IS NOT NULL THEN PLH.DRAFT_YEAR
        ELSE PST.DRAFT_YEAR
    END AS DRAFT_YEAR
    , CASE
        WHEN PLH.OVERALL_PICK IS NOT NULL THEN PLH.OVERALL_PICK
        ELSE PST.DRAFT_NUMBER
    END AS DRAFT_NUMBER
    , CASE
        WHEN PLH.DRAFT_TYPE IS NOT NULL THEN PLH.DRAFT_TYPE
        ELSE 'Unknown'
    END AS DRAFT_TYPE
    , CASE
        WHEN PLH.TEAM_NAME IS NOT NULL THEN PLH.TEAM_NAME
        ELSE PST.TEAM_ABREVIATION
    END AS TEAM_NAME
    , CASE
        WHEN PLH.TEAM_ABBREVIATION IS NOT NULL THEN PLH.TEAM_ABBREVIATION
        ELSE PST.TEAM_ABREVIATION
    END AS TEAM_ABBREVIATION
    , CASE
        WHEN PLH.TEAM_NICKNAME IS NOT NULL THEN PLH.TEAM_NICKNAME
        ELSE 'Unknown'
    END AS TEAM_NICKNAME
    , CASE
        WHEN PLH.TEAM_CITY IS NOT NULL THEN PLH.TEAM_CITY
        ELSE 'Unknown'
    END AS TEAM_CITY
    , CASE
        WHEN PLH.TEAM_ORGANIZTION IS NOT NULL THEN PLH.TEAM_ORGANIZTION
        ELSE PST.COLLEGE_NAME
    END AS COLLEGE_OR_TEAM_NAME
    , CASE
        WHEN PLH.TEAM_ORGANIZTION_TYPE IS NOT NULL THEN PLH.TEAM_ORGANIZTION_TYPE
        ELSE 'Unknown'
    END AS TEAM_ORGANIZTION_TYPE
    , PST.YEARS_PLAYED
    , PST.GAMES_PLAYED
    , PST.TOTAL_MINUTES_PLAYED
    , PST.TOTAL_POINTS
    , PST.TOTAL_REBOUNDS
    , PST.TOTAL_ASSISTS
    , PST.AVG_FG
    , PST.AVG_3PTM
    , PST.AVG_FT
    , PST.WIN_SHARED
    , PST."BOX +/-"
    , PST.VORP
    , PST.POINTS_PER_GAME
    , PST.REBOUNDS_PER_GAME
    , PST.ASSISTS_PER_GAME
    , 1 AS IS_VALID
     , TO_TIMESTAMP(CURRENT_TIMESTAMP ) AS LOAD_DATE
    , 'NBA_DB.CLEANSE_NBA_DATA.CLS_DRAFT_PLAYER_HISTORY' AS SOURCE_TABLE_1
    , 'NBA_DB.CLEANSE_NBA_DATA.CLS_DRAFT_PLAYER_STATS' AS SOURCE_TABLE_2
FROM CTE PLH
FULL JOIN CTF PST 
ON PST.DRAFT_YEAR = PLH.DRAFT_YEAR AND PST.DRAFT_NUMBER = PLH.OVERALL_PICK
),

CTII AS (
    SELECT 
        *
        , ROW_NUMBER() OVER (PARTITION BY PLAYER_FULL_NAME ORDER BY SEASON DESC) AS RN 
    FROM {{ ref('CLS_DRAFT_PLAYER_COMBINE_STATS') }}
),

CTI AS (
    SELECT 
        *
    FROM CTII
    WHERE RN = 1
)

SELECT 
    CTG.PLAYER_FULL_NAME
    , DPS.PLAYER_MAIN_POSITION
    , DPS.PLAYER_SECOND_POSITION
    , CTG.DRAFT_YEAR
    , CTG.DRAFT_NUMBER
    , CTG.DRAFT_TYPE
    , CTG.TEAM_NAME
    , CTG.TEAM_ABBREVIATION
    , CTG.TEAM_NICKNAME
    , CTG.TEAM_CITY
    , CTG.COLLEGE_OR_TEAM_NAME
    , CTG.TEAM_ORGANIZTION_TYPE
    , DPS.PLAYER_HEIGHT_IN_CM
    , DPS.PLAYER_WEIGHT_IN_KG
    , DPS.PLAYER_WINGSPAN_IN_CM
    , DPS.PLAYER_STANDING_REACH_IN_CM
    , DPS.PLAYER_BODY_FAT_PCT
    , DPS.PLAYER_HAND_LENGTH_IN_CM
    , DPS.PLAYER_HAND_WIDTH_IN_CM
    , DPS.DRAFT_STANDING_VERTICAL_LEAP_IN_CM
    , DPS.DRAFT_MAX_VERTICAL_LEAP_IN_CM
    , DPS.DRAFT_LANE_AGILITY_TIME
    , DPS.DRAFT_THREE_QUARTER_SPRINT
    , DPS.DRAFT_BENCH_PRESS_RESULT
    , DPS.DRAFT_SPOT_FIFTEEN_SUMMARY_PCT
    , DPS.DRAFT_SPOT_COLLEGE_SUMMARY_PCT
    , DPS.DRAFT_SPOT_NBA_SUMMARY_PCT
    , DPS.DRAFT_OFF_DRIB_FIFTEEN_SUMMARY_PCT
    , DPS.DRAFT_OFF_DRIB_COLLEGE_SUMMARY_PCT
    , DPS.DRAFT_ON_MOVE_FIFTEEN_SHOT_MAD
    , DPS.DRAFT_ON_MOVE_FIFTEEN_SHOT_ATT
    , DPS.DRAFT_ON_MOVE_FIFTEEN_SUMMARY_PCT
    , DPS.DRAFT_ON_MOVE_COLLEGE_SHOT_MAD
    , DPS.DRAFT_ON_MOVE_COLLEGE_SHOT_ATT
    , DPS.DRAFT_ON_MOVE_COLLEGE_SUMMARY_PCT
    , CTG.YEARS_PLAYED
    , CTG.GAMES_PLAYED
    , CTG.TOTAL_MINUTES_PLAYED
    , CTG.TOTAL_POINTS
    , CTG.TOTAL_REBOUNDS
    , CTG.TOTAL_ASSISTS
    , CTG.AVG_FG
    , CTG.AVG_3PTM
    , CTG.AVG_FT
    , CTG.WIN_SHARED
    , CTG."BOX +/-"
    , CTG.VORP
    , CTG.POINTS_PER_GAME
    , CTG.REBOUNDS_PER_GAME
    , CTG.ASSISTS_PER_GAME
    , CTG.IS_VALID
    , CTG.LOAD_DATE
    , CTG.SOURCE_TABLE_1
    , CTG.SOURCE_TABLE_2
    , CASE
        WHEN DPS.SOURCE_TABLE IS NULL THEN 'Not exists'
        ELSE DPS.SOURCE_TABLE 
    END AS SOURCE_TABLE_3
FROM CTG 
LEFT JOIN CTI DPS ON CTG.PLAYER_FULL_NAME = DPS.PLAYER_FULL_NAME
ORDER BY CTG.DRAFT_YEAR, CTG.DRAFT_NUMBER