with cte as (
    SELECT 
        * 
    from {{ ref('CLS_SEASPLAY_PLAYER_STATS') }}
    ),

CTF AS (
SELECT 
    SEASON_YEAR
    , TEAM_NAME
    , PLAYER_FULL_NAME
    , GAME_TYPE
    , SUM((PLAYER_MINUTES_PLAYED * 60 + PLAYER_SECONDS_PLAYED)) AS PLAYER_TIME_PLAYED
    , SUM(PLAYER_FG_MADE) AS  PLAYER_FG_MADE
    , SUM(PLAYER_FG_ATTEMPTED) AS PLAYER_FG_ATTEMPTED
    , SUM(PLAYER_3PT_MADE) AS PLAYER_3PT_MADE
    , SUM(PLAYER_3PT_ATTEMPTED) AS PLAYER_3PT_ATTEMPTED
    , SUM(PLAYER_FT_MADE) AS PLAYER_FT_MADE
    , SUM(PLAYER_FT_ATTEMPTED) AS PLAYER_FT_ATTEMPTED
    , SUM(PLAYER_OFF_REB) AS PLAYER_OFF_REB
    , SUM(PLAYER_DEF_REB) AS PLAYER_DEF_REB
    , SUM(PLAYER_TOTAL_REB) AS PLAYER_TOTAL_REB
    , SUM(PLAYER_AST) AS PLAYER_AST
    , SUM(PLAYER_STL) AS PLAYER_STL
    , SUM(PLAYER_BLK) AS PLAYER_BLK
    , SUM(PLAYER_TOV) AS PLAYER_TOV
    , SUM(PLAYER_FOULS) AS PLAYER_FOULS
    , SUM(PLAYER_PTS) AS PLAYER_PTS
    , CAST(AVG(PLAYER_PLUS_MINUS) AS NUMBER) AS PLAYER_PLUS_MINUS
    , COUNT(PLAYER_SECONDS_PLAYED) AS PLAYER_GAME_PLAYED
    , 1 AS IS_VALID
    , TO_TIMESTAMP(CURRENT_TIMESTAMP ) AS LOAD_DATE
    , 'CLEANSE_NBA_DATA.CLS_SEASPLAY_PLAYER_STATS' AS SOURCE_TABLE
FROM CTE
WHERE PLAYER_SECONDS_PLAYED IS NOT NULL
GROUP BY SEASON_YEAR
    , TEAM_NAME
    , PLAYER_FULL_NAME
    , GAME_TYPE)

SELECT 
    SEASON_YEAR
    , TEAM_NAME
    , PLAYER_FULL_NAME
    , GAME_TYPE
    , PLAYER_FG_MADE
    , PLAYER_FG_ATTEMPTED
    , CASE
        WHEN PLAYER_FG_ATTEMPTED <> 0 THEN ROUND(PLAYER_FG_MADE / PLAYER_FG_ATTEMPTED, 4)
        ELSE 0
    END AS PLAYER_FG_PCT
    , PLAYER_3PT_MADE
    , PLAYER_3PT_ATTEMPTED
    , CASE
        WHEN PLAYER_3PT_ATTEMPTED <> 0 THEN ROUND(PLAYER_3PT_MADE / PLAYER_3PT_ATTEMPTED, 4)
        ELSE 0
    END AS PLAYER_3PT_PCT
    , PLAYER_FT_MADE
    , PLAYER_FT_ATTEMPTED
    , CASE
        WHEN PLAYER_FT_ATTEMPTED <> 0 THEN ROUND(PLAYER_FT_MADE / PLAYER_FT_ATTEMPTED, 4)
        ELSE 0
    END AS PLAYER_FT_PCT
    , PLAYER_OFF_REB
    , PLAYER_DEF_REB
    , PLAYER_TOTAL_REB
    , PLAYER_AST
    , PLAYER_STL
    , PLAYER_BLK
    , PLAYER_TOV
    , PLAYER_FOULS
    , PLAYER_PTS
    , ROUND(PLAYER_OFF_REB / PLAYER_GAME_PLAYED, 2) AS PLAYER_OFF_REB_AVG
    , ROUND(PLAYER_DEF_REB / PLAYER_GAME_PLAYED, 2) AS PLAYER_DEF_REB_AVG
    , ROUND(PLAYER_TOTAL_REB / PLAYER_GAME_PLAYED, 2) AS PLAYER_TOTAL_REB_AVG
    , ROUND(PLAYER_AST / PLAYER_GAME_PLAYED, 2) AS PLAYER_AST_AVG
    , ROUND(PLAYER_STL / PLAYER_GAME_PLAYED, 2) AS PLAYER_STL_AVG
    , ROUND(PLAYER_BLK / PLAYER_GAME_PLAYED, 2) AS PLAYER_BLK_AVG
    , ROUND(PLAYER_TOV / PLAYER_GAME_PLAYED, 2) AS PLAYER_TOV_AVG
    , ROUND(PLAYER_FOULS / PLAYER_GAME_PLAYED, 2) AS PLAYER_FOULS_AVG
    , ROUND(PLAYER_PTS / PLAYER_GAME_PLAYED, 2) AS PLAYER_PTS_AVG
    , PLAYER_PLUS_MINUS
    , PLAYER_GAME_PLAYED
    , 1 AS IS_VALID
    , TO_TIMESTAMP(CURRENT_TIMESTAMP ) AS LOAD_DATE
    , 'CLEANSE_NBA_DATA.CLS_SEASPLAY_PLAYER_STATS' AS SOURCE_TABLE
FROM CTF