with cte as (
select * FROM {{ ref('CLS_ALL_COMMON_PLAYER_INFO') }}
where is_same_name = 'Regular'
),

ctF as (
select * FROM {{ ref('CLS_ALL_COMMON_PLAYER_INFO') }}
where is_same_name = 'Other' AND DRAFT_YEAR <> 'Undrafted'
),

CTG AS (SELECT * FROM {{ ref('CO_SEASON_PLAYER_STARS_WO_DETAILS') }} 
WHERE IS_SAME_NAME = 'Regular'),

CTH AS (SELECT * FROM {{ ref('CO_SEASON_PLAYER_STARS_WO_DETAILS') }} 
WHERE IS_SAME_NAME = 'Other'),

CTI AS(
SELECT 
    DTS.PLAYER_FULL_NAME AS PLAYER_FULL_NAME
    , CPI.PLAYER_BIRTH_DATE
    , DTS.PLAYER_SEASON_PLAYED
    , CPI.PLAYER_SCHOOL
    , CPI.PLAYER_COUNTRY
    , CPI.PLAYER_PREVIOUS_TEAM
    , CPI.PLAYER_PREVIOUS_TEAM_COUNTRY
    , CPI.DRAFT_YEAR  AS PLAYER_DRAFT_YEAR
    , CPI.DRAFT_ROUND AS PLAYER_DRAFT_ROUND
    , CPI.DRAFT_NUMBER AS PLAYER_DRAFT_NUMBER
    , CPI.IS_GREATEST_75 AS PLAYER_IS_GREATEST_75
    , DTS.START_OF_SEASON AS SEASON_START_YEAR
    , DTS.END_OF_SEASON  AS SEASON_END_YEAR
    , CPI.PLAYER_HEIGHT_IN_CM
    , CPI.PLAYER_WEIGHT_IN_KG
    , CPI.PLAYER_SEASON_EXPERIENCE
    , CPI.PLAYER_MAIN_POSITION
    , CPI.PLAYER_SECOND_POSITION
    , CPI.PLAYER_ROSTER_STATUS
    , CPI.PLAYED_IN_DLEAGUE
    , CPI.TEAM_NAME
    , CPI.TEAM_NICKNAME
    , DTS.TEAM_ABBREVIATION
    , CPI.TEAM_CITY
    , CPI.TEAM_FOUND_YEAR
    , CPI.TEAM_TILL_YEAR
    , DTS.PLAYER_AGE
    , DTS.PLAYER_GAMES_PLAYED
    , DTS.PLAYER_GAMES_STARTED
    , DTS.PLAYER_MINUTES_PLAYED
    , DTS.PLAYER_FG_MADE
    , DTS.PLAYER_FG_ATTEMPTED
    , DTS.PLAYER_FG_PCT
    , DTS.PLAYER_3PT_MADE
    , DTS.PLAYER_3PT_ATTEMPTED
    , DTS.PLAYER_3PT_PCT
    , DTS.PLAYER_FT_MADE
    , DTS.PLAYER_FT_ATTEMMPTED
    , DTS.PLAYER_FT_PCT
    , DTS.PLAYER_OFF_REB
    , DTS.PLAYER_DEF_REB
    , DTS.PLAYER_TOT_REB
    , DTS.PLAYER_ASSISTS
    , DTS.PLAYER_STEALS
    , DTS.PLAYER_BLOCKS
    , DTS.PLAYER_TOVERS
    , DTS.PLAYER_FOULS
    , DTS.PLAYER_POINTS
    , DTS.IS_VALID
    , TO_TIMESTAMP(CURRENT_TIMESTAMP ) AS LOAD_DATE
    , 'NBA_DB.CORE_NBA_DATA.CO_SEASON_PLAYER_STARS_WO_DETAILS' AS SOURCE_TABLE_1
    , 'NBA_DB.CLEANSE_NBA_DATA.CLS_ALL_COMMON_PLAYER_INFO' AS SOURCE_TABLE_2 
FROM CTG DTS
LEFT JOIN CTE CPI
ON DTS.PLAYER_FULL_NAME = CPI.PLAYER_FULL_NAME),

CTJ AS (
SELECT 
    DTS.PLAYER_FULL_NAME AS PLAYER_FULL_NAME
    , CPI.PLAYER_BIRTH_DATE
    , DTS.PLAYER_SEASON_PLAYED
    , CPI.PLAYER_SCHOOL
    , CPI.PLAYER_COUNTRY
    , CPI.PLAYER_PREVIOUS_TEAM
    , CPI.PLAYER_PREVIOUS_TEAM_COUNTRY
    , CPI.DRAFT_YEAR  AS PLAYER_DRAFT_YEAR
    , CPI.DRAFT_ROUND AS PLAYER_DRAFT_ROUND
    , CPI.DRAFT_NUMBER AS PLAYER_DRAFT_NUMBER
    , CPI.IS_GREATEST_75 AS PLAYER_IS_GREATEST_75
    , DTS.START_OF_SEASON AS SEASON_START_YEAR
    , DTS.END_OF_SEASON  AS SEASON_END_YEAR
    , CPI.PLAYER_HEIGHT_IN_CM
    , CPI.PLAYER_WEIGHT_IN_KG
    , CPI.PLAYER_SEASON_EXPERIENCE
    , CPI.PLAYER_MAIN_POSITION
    , CPI.PLAYER_SECOND_POSITION
    , CPI.PLAYER_ROSTER_STATUS
    , CPI.PLAYED_IN_DLEAGUE
    , CPI.TEAM_NAME
    , CPI.TEAM_NICKNAME
    , DTS.TEAM_ABBREVIATION
    , CPI.TEAM_CITY
    , CPI.TEAM_FOUND_YEAR
    , CPI.TEAM_TILL_YEAR
    , DTS.PLAYER_AGE
    , DTS.PLAYER_GAMES_PLAYED
    , DTS.PLAYER_GAMES_STARTED
    , DTS.PLAYER_MINUTES_PLAYED
    , DTS.PLAYER_FG_MADE
    , DTS.PLAYER_FG_ATTEMPTED
    , DTS.PLAYER_FG_PCT
    , DTS.PLAYER_3PT_MADE
    , DTS.PLAYER_3PT_ATTEMPTED
    , DTS.PLAYER_3PT_PCT
    , DTS.PLAYER_FT_MADE
    , DTS.PLAYER_FT_ATTEMMPTED
    , DTS.PLAYER_FT_PCT
    , DTS.PLAYER_OFF_REB
    , DTS.PLAYER_DEF_REB
    , DTS.PLAYER_TOT_REB
    , DTS.PLAYER_ASSISTS
    , DTS.PLAYER_STEALS
    , DTS.PLAYER_BLOCKS
    , DTS.PLAYER_TOVERS
    , DTS.PLAYER_FOULS
    , DTS.PLAYER_POINTS
    , DTS.IS_VALID
    , TO_TIMESTAMP(CURRENT_TIMESTAMP ) AS LOAD_DATE
    , 'NBA_DB.CORE_NBA_DATA.CO_SEASON_PLAYER_STARS_WO_DETAILS' AS SOURCE_TABLE_1
    , 'NBA_DB.CLEANSE_NBA_DATA.CLS_ALL_COMMON_PLAYER_INFO' AS SOURCE_TABLE_2 
FROM CTH DTS
LEFT JOIN CTF CPI
ON DTS.PLAYER_FULL_NAME = CPI.PLAYER_FULL_NAME
AND DTS.PROBABLE_DRAFT_YEAR = CPI.DRAFT_YEAR
)

SELECT * FROM CTI
UNION ALL
SELECT * FROM CTJ