WITH CTE AS (
SELECT DISTINCT(PLAYER_ID) AS PLAYER_ID, PLAYER_FULL_NAME
FROM {{ ref('CLS_SEASON_PLAYER_DATASET') }}
), 

CTF AS (
SELECT 
    CTE.PLAYER_ID AS PLAYER_ID_I
    , CTE.PLAYER_FULL_NAME
    , DTS.PLAYER_ID AS PLAYER_ID_II
    , DTS.PLAYER_FULL_NAME AS NAME_II 
FROM CTE
LEFT JOIN (SELECT DISTINCT(PLAYER_ID) AS PLAYER_ID, PLAYER_FULL_NAME
FROM {{ ref('CLS_SEASON_PLAYER_DATASET') }}) DTS
ON CTE.PLAYER_FULL_NAME = DTS.PLAYER_FULL_NAME
WHERE CTE.PLAYER_ID <> DTS.PLAYER_ID
),

CTG AS (
SELECT 
    PLAYER_ID_I AS CTG_PLAYER_ID
    , PLAYER_FULL_NAME
FROM CTF
),

CTH AS (
SELECT 
    CTG_PLAYER_ID AS PLAYER_ID
    , 'Other' AS IS_SAME_NAME
FROM CTG
),

CTI AS (
    SELECT 
        DTS.*
        , CTH.IS_SAME_NAME
    FROM {{ ref('CLS_SEASON_PLAYER_DATASET') }} DTS
    LEFT JOIN CTH ON DTS.PLAYER_ID = CTH.PLAYER_ID
),

CTJ AS (
SELECT 
    PLAYER_ID
    , PLAYER_FULL_NAME
    , PLAYER_SEASON_PLAYED
    , START_OF_SEASON
    , END_OF_SEASON
    , TEAM_FULL_NAME
    , TEAM_ABBREVIATION
    , TEAM_CITY
    , CAST(PLAYER_AGE AS NUMBER) AS PLAYER_AGE
    , PLAYER_GAMES_PLAYED
    , PLAYER_GAMES_STARTED
    , PLAYER_MINUTES_PLAYED
    , PLAYER_FG_MADE
    , PLAYER_FG_ATTEMPTED
    , PLAYER_FG_PCT
    , PLAYER_3PT_MADE
    , PLAYER_3PT_ATTEMPTED
    , PLAYER_3PT_PCT
    , PLAYER_FT_MADE
    , PLAYER_FT_ATTEMMPTED
    , PLAYER_FT_PCT
    , PLAYER_OFF_REB
    , PLAYER_DEF_REB
    , PLAYER_TOT_REB
    , PLAYER_ASSISTS
    , PLAYER_STEALS
    , PLAYER_BLOCKS
    , PLAYER_TOVERS
    , PLAYER_FOULS
    , PLAYER_POINTS
    , IS_VALID
    , LOAD_DATE
    , SOURCE_TABLE
    , CASE
        WHEN IS_SAME_NAME IS NULL THEN 'Regular'
        ELSE IS_SAME_NAME
    END AS IS_SAME_NAME
    , 0 AS PROBABLE_DRAFT_YEAR
FROM CTI
WHERE TEAM_ABBREVIATION <> 'TOT'
),

CTK1 AS (
SELECT 
    PLAYER_ID
    , INITCAP(PLAYER_FULL_NAME) AS PLAYER_FULL_NAME
    , PLAYER_SEASON_PLAYED
    , START_OF_SEASON
    , END_OF_SEASON
    , TEAM_FULL_NAME
    , TEAM_ABBREVIATION
    , TEAM_CITY
    , PLAYER_AGE
    , PLAYER_GAMES_PLAYED
    , PLAYER_GAMES_STARTED
    , PLAYER_MINUTES_PLAYED
    , PLAYER_FG_MADE
    , PLAYER_FG_ATTEMPTED
    , PLAYER_FG_PCT
    , PLAYER_3PT_MADE
    , PLAYER_3PT_ATTEMPTED
    , PLAYER_3PT_PCT
    , PLAYER_FT_MADE
    , PLAYER_FT_ATTEMMPTED
    , PLAYER_FT_PCT
    , PLAYER_OFF_REB
    , PLAYER_DEF_REB
    , PLAYER_TOT_REB
    , PLAYER_ASSISTS
    , PLAYER_STEALS
    , PLAYER_BLOCKS
    , PLAYER_TOVERS
    , PLAYER_FOULS
    , PLAYER_POINTS
    , IS_VALID
    , TO_TIMESTAMP(CURRENT_TIMESTAMP ) AS LOAD_DATE
    , 'CLEANSE_NBA_DATA.CLS_SEASON_PLAYER_DATASET' SOURCE_TABLE
    , 'Regular' IS_SAME_NAME
    , 0 AS PROBABLE_DRAFT_YEAR 
FROM CTJ
WHERE IS_SAME_NAME = 'Regular' AND PLAYER_FULL_NAME NOT IN ('Charles Jones','Charlie Davis','Dee Brown','George Johnson','Gerald Henderson',
'Glen Rice','Greg Smith','Jim Paxson','Johnny Davis','Larry Johnson','Mike James','Reggie Williams','Steven Smith','Walker Russell'
)
),

CTK2 AS (
SELECT 
    PLAYER_ID
    , INITCAP(PLAYER_FULL_NAME) AS PLAYER_FULL_NAME
    , PLAYER_SEASON_PLAYED
    , START_OF_SEASON
    , END_OF_SEASON
    , TEAM_FULL_NAME
    , TEAM_ABBREVIATION
    , TEAM_CITY
    , PLAYER_AGE
    , PLAYER_GAMES_PLAYED
    , PLAYER_GAMES_STARTED
    , PLAYER_MINUTES_PLAYED
    , PLAYER_FG_MADE
    , PLAYER_FG_ATTEMPTED
    , PLAYER_FG_PCT
    , PLAYER_3PT_MADE
    , PLAYER_3PT_ATTEMPTED
    , PLAYER_3PT_PCT
    , PLAYER_FT_MADE
    , PLAYER_FT_ATTEMMPTED
    , PLAYER_FT_PCT
    , PLAYER_OFF_REB
    , PLAYER_DEF_REB
    , PLAYER_TOT_REB
    , PLAYER_ASSISTS
    , PLAYER_STEALS
    , PLAYER_BLOCKS
    , PLAYER_TOVERS
    , PLAYER_FOULS
    , PLAYER_POINTS
    , IS_VALID
    , TO_TIMESTAMP(CURRENT_TIMESTAMP ) AS LOAD_DATE
    , 'CLEANSE_NBA_DATA.CLS_SEASON_PLAYER_DATASET' SOURCE_TABLE
    , 'Other' IS_SAME_NAME
     , MIN(START_OF_SEASON) OVER(PARTITION BY PLAYER_ID) AS PROBABLE_DRAFT_YEAR
FROM CTJ
WHERE IS_SAME_NAME = 'Regular' AND PLAYER_FULL_NAME IN ('Charles Jones','Charlie Davis','Dee Brown','George Johnson','Gerald Henderson',
'Glen Rice','Greg Smith','Jim Paxson','Johnny Davis','Larry Johnson','Mike James','Reggie Williams','Steven Smith','Walker Russell'
)
),

CTL AS (
SELECT 
    PLAYER_ID
    , PLAYER_FULL_NAME
    , PLAYER_SEASON_PLAYED
    , START_OF_SEASON
    , END_OF_SEASON
    , TEAM_FULL_NAME
    , TEAM_ABBREVIATION
    , TEAM_CITY
    , PLAYER_AGE
    , PLAYER_GAMES_PLAYED
    , PLAYER_GAMES_STARTED
    , PLAYER_MINUTES_PLAYED
    , PLAYER_FG_MADE
    , PLAYER_FG_ATTEMPTED
    , PLAYER_FG_PCT
    , PLAYER_3PT_MADE
    , PLAYER_3PT_ATTEMPTED
    , PLAYER_3PT_PCT
    , PLAYER_FT_MADE
    , PLAYER_FT_ATTEMMPTED
    , PLAYER_FT_PCT
    , PLAYER_OFF_REB
    , PLAYER_DEF_REB
    , PLAYER_TOT_REB
    , PLAYER_ASSISTS
    , PLAYER_STEALS
    , PLAYER_BLOCKS
    , PLAYER_TOVERS
    , PLAYER_FOULS
    , PLAYER_POINTS
    , IS_VALID
    , TO_TIMESTAMP(CURRENT_TIMESTAMP ) AS LOAD_DATE
    , 'CLEANSE_NBA_DATA.CLS_SEASON_PLAYER_DATASET' SOURCE_TABLE
    , 'Other' IS_SAME_NAME
    , MIN(START_OF_SEASON) OVER(PARTITION BY PLAYER_ID) AS PROBABLE_DRAFT_YEAR
FROM CTJ
WHERE IS_SAME_NAME = 'Other'
),

CTKK AS (
SELECT 
    PLAYER_ID
    , INITCAP(PLAYER_FULL_NAME) AS PLAYER_FULL_NAME
    , PLAYER_SEASON_PLAYED
    , START_OF_SEASON
    , END_OF_SEASON
    , TEAM_FULL_NAME
    , TEAM_ABBREVIATION
    , TEAM_CITY
    , PLAYER_AGE
    , PLAYER_GAMES_PLAYED
    , PLAYER_GAMES_STARTED
    , PLAYER_MINUTES_PLAYED
    , PLAYER_FG_MADE
    , PLAYER_FG_ATTEMPTED
    , PLAYER_FG_PCT
    , PLAYER_3PT_MADE
    , PLAYER_3PT_ATTEMPTED
    , PLAYER_3PT_PCT
    , PLAYER_FT_MADE
    , PLAYER_FT_ATTEMMPTED
    , PLAYER_FT_PCT
    , PLAYER_OFF_REB
    , PLAYER_DEF_REB
    , PLAYER_TOT_REB
    , PLAYER_ASSISTS
    , PLAYER_STEALS
    , PLAYER_BLOCKS
    , PLAYER_TOVERS
    , PLAYER_FOULS
    , PLAYER_POINTS
    , IS_VALID
    , LOAD_DATE
    , SOURCE_TABLE
    , IS_SAME_NAME
     , CASE
        WHEN PLAYER_FULL_NAME = 'Charles Jones' THEN 1979
        WHEN PLAYER_FULL_NAME = 'Gerald Henderson' THEN 1978
    else PROBABLE_DRAFT_YEAR
    end as PROBABLE_DRAFT_YEAR
 FROM CTK2 
),

CTM AS (
SELECT * FROM CTK1
UNION ALL
SELECT * FROM CTKK
UNION ALL
SELECT * FROM CTL
)

SELECT * FROM CTM