nba_dbt:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: uxqdofj-rz91466
      user: cubix181818
      password: AbukSpox11..11
      role: ACCOUNTADMIN
      database: NBA_DB
      warehouse: COMPUTE_WH
      schema: PLAYER_DATA
      threads: 1
      client_session_keep_alive: False