nba_dbt:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: PFGVLRU-AQ83100
      user: Cubix9629
      password: AbukSpox11..11
      role: ACCOUNTADMIN
      database: NBA_DB
      warehouse: COMPUTE_WH
      schema: PLAYER_DATA
      threads: 1
      client_session_keep_alive: False
