WITH CTE AS (
    SELECT 
        HOME_TEAM_NAME
        , AVG(HOME_SCORE) AS AVG_HOME 
    FROM {{ ref('CLS_REG_SEASON24_API') }}
    GROUP BY HOME_TEAM_NAME), 

CTF AS (
    SELECT 
        VISITOR_TEAM_NAME
        , AVG(VISITOR_SCORE) AS AVG_AWAY 
    FROM {{ ref('CLS_REG_SEASON24_API') }}
    GROUP BY VISITOR_TEAM_NAME)

SELECT 
    CTE.HOME_TEAM_NAME
    , CTE.AVG_HOME
    , CTF.AVG_AWAY
    , ((41 * CTE.AVG_HOME + 41 * CTF.AVG_AWAY)/82) AS ALL_POINTS 
FROM CTE
LEFT JOIN CTF ON CTE.HOME_TEAM_NAME = CTF.VISITOR_TEAM_NAME
ORDER BY 4 DESC