version: 2

models:
  - name: MART_REG_SEASON24_API_TEAM_SCORE
    description: >
      Model agregujący punkty zdobyte przez drużyny gospodarzy i gości.
      Służy jako źródło dla dalszych analiz efektywności zespołów.
    columns:
      - name: home_team_name
        description: Nazwa drużyny gospodarza
        tests:
          - not_null
      - name: total_home_score
        description: Suma punktów zdobytych przez gospodarzy
        tests:
          - not_null
      - name: total_visitor_score
        description: Suma punktów zdobytych przez drużyny przyjezdne
        tests:
          - not_null
  - name: MART_REG_SEASON24_API_TEAM_SUMMARY
    description: >
      Model agregujący dane, ale liczący średnią z całego sezonu.
    columns:
      - name: home_team_name
        description: Nazwa drużyny gospodarza
        tests:
          - not_null
        name: visitor_team_name
        description: Nazwa drużyny gości
        tests:
          - not_null
      - name: avg_home
        description: Suma punktów zdobytych przez gospodarzy
        tests:
          - not_null
      - name: avg_away
        description: Suma punktów zdobytych przez drużyny przyjezdne
        tests:
          - not_null
        name: all_points
        description: Średnia z wszystkich punktów
        tests:
          - not_null