
WITH CTE AS (
    SELECT 
        CASE 
            WHEN TEAM_ABREVIATION = 'PHO' THEN 'PHX'
            WHEN TEAM_ABREVIATION = 'BRK' THEN 'BKN'
            ELSE TEAM_ABREVIATION
        END AS TEAM_ABREVIATION
        , PLAYER_ID
        , MD5(COLLEGE_NAME) AS COLLEGE_ID
        , YEARS_PLAYED
        , GAMES_PLAYED
        , TOTAL_MINUTES_PLAYED
        , TOTAL_POINTS
        , TOTAL_REBOUNDS
        , TOTAL_ASSISTS
        , AVG_FG
        , AVG_3PTM
        , AVG_FT
        , WIN_SHARED
        , POINTS_PER_GAME
        , REBOUNDS_PER_GAME
        , ASSISTS_PER_GAME
    FROM {{ref("CLS_NBA_DRAFT_DATA")}}
),

CTF AS (
SELECT 
    DISTINCT MD5(DRAFT.TEAM_ABREVIATION || SEASON.TEAM_NAME) AS TEAM_ID
    , TEAM_ABREVIATION
    , SEASON.TEAM_NAME
    , SEASON.TEAM_CITY
FROM CTE DRAFT
LEFT JOIN (SELECT DISTINCT TEAM_ABBREVATION, TEAM_NAME, TEAM_CITY FROM {{ref("CLS_REG_SEASON_STATS_ALL") }} 
            WHERE TEAM_CITY <> 'LA' AND TEAM_NAME <> 'Bobcats') SEASON
ON DRAFT.TEAM_ABREVIATION = SEASON.TEAM_ABBREVATION
        )
        
SELECT 
    CTE.PLAYER_ID
    , CTE.COLLEGE_ID
    , CTF.TEAM_ID
    , CTE.YEARS_PLAYED
    , CTE.GAMES_PLAYED
    , CTE.TOTAL_MINUTES_PLAYED
    , CTE.TOTAL_POINTS
    , CTE.TOTAL_REBOUNDS
    , CTE.TOTAL_ASSISTS
    , CTE.AVG_FG
    , CTE.AVG_3PTM
    , CTE.AVG_FT
    , CTE.WIN_SHARED
    , CTE.POINTS_PER_GAME
    , CTE.REBOUNDS_PER_GAME
    , CTE.ASSISTS_PER_GAME
FROM CTE
LEFT JOIN CTF
ON CTE.TEAM_ABREVIATION = CTF.TEAM_ABREVIATION