
WITH CTE AS (
    SELECT 
        CASE 
            WHEN TEAM_ABREVIATION = 'PHO' THEN 'PHX'
            WHEN TEAM_ABREVIATION = 'BRK' THEN 'BKN'
            ELSE TEAM_ABREVIATION
        END AS TEAM_ABREVIATION
    FROM {{ ref('CLS_NBA_DRAFT_DATA') }}
)

SELECT 
    DISTINCT MD5(DRAFT.TEAM_ABREVIATION || SEASON.TEAM_NAME) AS TEAM_ID
    , TEAM_ABREVIATION
    , SEASON.TEAM_NAME
    , SEASON.TEAM_CITY
FROM CTE DRAFT
LEFT JOIN (SELECT DISTINCT TEAM_ABBREVATION, TEAM_NAME, TEAM_CITY FROM {{ ref('CLS_REG_SEASON_STATS_ALL') }} 
            WHERE TEAM_CITY <> 'LA') SEASON
ON DRAFT.TEAM_ABREVIATION = SEASON.TEAM_ABBREVATION
